/* eslint-disable max-len */
const AppConstants = {
  languages: 'Languages',
  culture: 'Culture',
  occupation: 'Occupation',
  participant_firstName: 'Participant First/Preferred Name',
  firstName: 'First/Preferred Name',
  enterFirstName: 'Enter First/Preferred Name',
  emergencyFirstName: 'Emergency First/Preferred Name',
  umpireAllocation: 'Umpire Allocation',
  gameTimeTracking: 'Special Competition - Game Time Tracking',
  positionAbbr: 'POS',
  position: 'Positions Played',
  missAbbr: 'M',
  miss: 'Misses',
  titleGames: 'TOC(G)',
  titlePeriods: 'TOC(P)',
  externalUserId: 'External User ID',
  userPhoto: 'Photo',
  titleMinutes: 'TOC(M)',
  playedGames: 'Time on Court in Games',
  playedPeriods: 'Time on Court in Periods',
  playedMinutes: 'Time on Court in Minutes',
  unitGames: 'game(s)',
  unitMinutes: 'min(s)',
  unitPeriods: 'period(s)',
  teamYouFollow: 'Which Suncorp Super Netball Team do you follow?',
  umpireChangedMatchDayMessage: 'You have edited an Umpire. Please publish this allocation via the Umpire module.',
};

export default AppConstants;
