const ValidationConstants = {
  divisionField: 'Age Group field is required.',
  homeField: 'Home team is required.',
  awayField: 'Away team is required.',
  venueField: 'Venue is required.',
  divisionFieldRequired: 'Age Group field is required',
  gradeFieldRequired: 'Division field is required',
  courtFieldRequired: 'Field is required',
  courtNamePlaceHolder: 'Field Name',
  selectMinuteHourSecond: 'Please select one of the field Hours/Minutes/seconds',
  court: 'Field is required.',
  divisionStartDate: 'Please select Age Group Start Date',
  startDateIsRequired: 'Start date is required.',
  endDateIsRequired: 'End date is required',
  divisionName: 'Age Group Name field is required.',
  courtRotationRequired: 'Field rotation is required',
  gradeNameRequired: 'Division name is required',
  pleaseAddDivisionForMembershipProduct: 'Please enter age groups before proceeding.',
  umpireSearch: 'Referee search is required.',
  umpireMessage: 'This referee has not been linked to a user profile',
  divisionAndTimeslot: 'Please select Age Group and Timeslot',
  recordUmpireField: 'Allocate referee is required.',
  pleaseSelectBetweenUmpireAndCoach: 'User must be referee, Referee Assessor or both',
  pleaseSelectGradesOrPools: 'Please select Division or Pools',
  pleaseFillDivisionBeforePublishing: 'Please fill Age Group before publishing.',
  accreditationLevelUmpire: 'National accreditation level referee is required.',
  nationalMembershipProductIsRequired: 'Please select National Membership Product',
  missingDrawSettingMsg: 'Note: Both age groups and rounds must be specified when hiding draws',
  selectBothDivAndRound: 'Please specify both age groups and rounds',
  missingLadderSettingMsg: 'Note: Both age groups and rounds must be specified when hiding ladders',
  pleaseEnterGradeName: 'Please enter division name',
  selectDivisionsForNamingFormat: 'Please select Age Groups for the naming format',
};

export default ValidationConstants;
