const ValidationConstants = {
  nameField: [
    'Name is required.',
    'Last name is required.',
    'Name is required.',
    'Short name is required',
    'First name is required',
  ],
  teamName: 'Team name is required',
  firstName: 'Name is required.',
  lastName: 'Last name is required.',
  dateField: 'Date is required.',
  timeouts: 'Time Outs option is required.',
  divisionField: 'Division field is required.',
  field: 'Field is required.',
  typeField: 'Type is required.',
  homeField: 'Home team is required.',
  awayField: 'Away team is required.',
  venueField: 'Venue is required.',
  roundField: 'Round is required.',
  durationField: 'Duration time is required.',
  emailField: [
    'Email is required.',
    'Please enter valid email.',
    'After changing your email address, you will need to relogin with your new email address',
  ],
  contactField: 'Contact is required.',
  competitionField: 'Competition is required.',
  timerField: 'Timer is required.',
  newsValidation: ['News title is required.', 'Author is required'],
  communicationValidation: ['Communication title is required.', 'Author is required'],
  bannerImage: 'Banner image is required',
  moreBannerImage: 'At least one of Banner images is required',
  addressField: ['Address is required.'],
  searchManager: 'Manager search is required.',
  searchScorer: 'Scorer search is required.',
  affiliateField: 'Affiliate is required',
  rolesField: ['Roles field is mandatory'],
  genderField: 'Gender is required',
  dateOfBirth: 'DOB is required',
  membershipProductRequired: 'Please select the competition membership product',
  emergencyContactNumber: ['Emergency contact number is required'],
  emergencyContactName: [
    'Emergency contact first name is required',
    'Emergency contact last name is required',
  ],
  existingMedicalCondition: ['Existing Medical Conditions is required'],
  regularMedication: ['Regular Medications is required'],
  heardBy: ['HeardBy is required'],
  favoriteTeamField: ['Favorite Team is required'],
  firebirdField: ['Firebird is required'],
  termsAndCondition: ['Terms and Condition is required'],
  affiliateContactRequired: ['Affiliate should have atleast one contact with admin role'],
  requiredMessage: ['Please fill all the required fields'],
  drawsMessage: ['Something went wrong with draws generation'],
  finalGrading: ['Please provide final grade for all the teams'],
  proposedGrading: ['Please provide proposed grade for all the teams'],
  membershipProductIsRequired: 'Membership product name is required.',
  pleaseSelectValidity: 'Please select validity.',
  pleaseSelectYear: 'Please select Year.',
  pleaseSelectDOBFrom: 'Please select DOB From.',
  PleaseSelectDOBTo: 'Please select DOB To.',
  pleaseSelectMembershipTypes: 'Please select membership types.',
  competitionLogoIsRequired: 'Competition logo is required.',
  disclaimersIsRequired: 'Disclaimers is required.',
  DisclaimerLinkIsRequired: 'Disclaimer link is required.',
  pleaseSelectMembershipProduct: 'Please select membership product.',
  suburbField: ['Suburb is required.'],
  stateField: ['State field is required.'],
  dayField: ['Day field is required.'],
  courtFieldLatitude: 'Latitude field is required.',
  courtFieldLongitude: 'Longitude field is required.',
  divisionFieldRequired: 'Division field is required',
  gradeFieldRequired: 'Grade field is required',
  venueFieldRequired: 'Venue field is required',
  courtFieldRequired: 'Court field is required',
  courtNamePlaceHolder: 'Court Name',
  postCodeField: ['Postcode is required'],
  competitionNameIsRequired: 'Competition name is required.',
  organisationNameIsRequired: 'Organisation name is required.',
  pleaseSelectCompetitionType: 'Please select competition type.',
  pleaseSelectCompetitionFormat: 'Please select competition format.',
  pleaseSelectBannerFormat: 'Please select banner format.',
  numberOfRoundsNameIsRequired: 'Number of rounds is required.',
  registrationOpenDateIsRequired: 'Registration open date is required.',
  registrationCloseDateIsRequired: 'Registration close date is required.',
  timeSlotPreference: 'At least one timeslot must be entered',
  gradeField: 'Grade field is required.',
  messageStatus401: 'Your session has expired. Please login.',
  emptyAddCourtValidation: 'Please add court to add venue.',
  emptyGameDaysValidation: 'Please add game days to venue',
  divisionNameIsRequired: 'Division name is required.',
  gradeIsRequired: 'Grade is required.',
  selectMinuteHourSecond: 'Please select one of the field Hours/Minutes/seconds',
  timeField: 'Time is required.',
  pleaseSelect: 'Please select any option.',
  court: 'Court is required.',
  csvField: 'Please select CSV file.',
  compRegHaveBeenSent: 'Competition Registrations have been sent already.',
  feesCannotBeEmpty: 'Please select fees.',
  shortField: 'Short name is required.',
  pleaseSelectRegInvitees: 'Please select Registration Invitee.',
  compIsPublished: 'Competition is Published.',
  publishedInRegistration: 'Please publish competition in registration module.',
  specificTime: 'Please select Specific Time.',
  selectReason: 'Reason is required.',
  pleaseSelectCompetition: 'Please select competition',
  matchDuration: 'Please enter a match duration',
  evenMatchDuration: 'Please enter an even match duration',
  mainBreak: 'Please enter a main break',
  qtrBreak: 'Please enter a qtr break',
  timeBetweenGames: 'Please enter a time between games',
  divisionStartDate: 'Please select division startDate',
  startDateIsRequired: 'Start date is required.',
  endDateIsRequired: 'End date is required',
  divisionName: 'Division Name field is required.',
  genderRestriction: 'Please select gender.',
  matchTypeRequired: 'Please select match type',
  organisationPhotoRequired: 'Organisation photo is required',
  photoTypeRequired: 'Photo type is required',
  pleaseSelectVenue: 'Please select Venue',
  pleaseSelectRound: 'Please select round',
  homeTeamRotationRequired: 'Home team rotation is required',
  courtRotationRequired: 'Court rotation is required',
  finalsStartDateRequired: 'Finals start date is required',
  extraTimeMatchTypeRequired: 'Please select extra time type',
  extraTimeDurationRequired: 'Please enter extra time duration',
  extraTimeMainBreakRequired: 'Please enter extra time main break',
  extraTimeBreakRequired: 'Please enter extra time break',
  beforeExtraTimeRequired: 'Please enter before extra time',
  finalFixtureTemplateRequired: 'Please select final fixture template',
  extraTimeDrawRequired: 'Please select extra time draw',
  applyToRequired: 'Please select apply to',
  gradeNameRequired: 'Grade name is required',
  pleaseSelectDiscountType: 'Please select discount type.',
  affiliateToRequired: 'Please select affiliate to',
  playerMessage: 'This player has not been linked to a user profile',
  personMessage: 'This person has not been linked to a user profile',
  gameDayEndTimeValidation: 'Game day end time should be greater than start time',
  venueCourtEndTimeValidation: 'Venue court end time should be greater than start time',
  endTimeValidation: 'End time should be greater than start time',
  charityTitleNameIsRequired: 'Charity title is required.',
  coachSearch: 'Coach Search',
  searchCoach: 'Please search coach.',
  charityDescriptionIsRequired: 'Charity description is required.',
  pleaseAddDivisionForMembershipProduct: 'Please enter divisions before proceeding.',
  pleaseEnterChildDiscountPercentage: 'Please enter child discount.',
  pleaseSelectTeam: 'Please Select Team.',
  selectAbandonMatchReason: 'Please Select Reason.',
  umpireSearch: 'Umpire search is required.',
  umpireMessage: 'This umpire has not been linked to a user profile',
  enterTitleOfTheProduct: 'Please enter title of the product.',
  enterLengthOfTheProduct: 'Please enter length of the product.',
  enterWidthOfTheProduct: 'Please enter width of the product.',
  enterHeightOfTheProduct: 'Please enter height of the product.',
  enterWeightOfTheProduct: 'Please enter weight of the product.',
  pleaseEnterProductType: 'Please enter product type.',
  pleaseEnterVariantName: 'Please enter variant name.',
  SelectNumberTeam: 'Please add number of Teams',
  email_validation: 'Please enter valid email address!',
  matchDeleteMsg: 'This match cannot be deleted as it has already ended.',
  userNotFound: 'No matching user was found.',
  incidentName: 'Incident name is required.',
  divisionAndTimeslot: 'Please select Division and Timeslot',
  pleaseSelectAffiliate: 'Please select one affiliate.',
  incidentPlayer: 'Player name is required',
  point: 'Point is required.',
  reasonChange: 'Reason is required.',
  userName: 'User name is required.',
  competitionAdministrator: 'Competition administrator is required',
  compStartDate: 'Competition start date is required',
  pleaseEnterQuantity: 'Please enter quantity.',
  recordUmpireField: 'Allocate umpire is required.',
  attendanceRecordField: 'Record is required.',
  attendanceReportField: 'Report is required.',
  scoringField: 'Scoring is required.',
  enterAddress: 'Please enter address.',
  passwordVerification: 'Password must be minimum 8 characters',
  venueAddressDetailsError: 'Please select a venue which has a street address',
  duplicatedVenueAddressError: 'Venue address is duplicated, please select other address',
  duplicateDiscountError: 'Please remove the duplicate entry of Discount Code.',
  mnbMatchId: 'mnbMatchId is required',
  pleaseSelectOneOption: 'Please select any option.',
  pleaseProvideInstalmentDate: 'Please provide an instalment date',
  pleaseEnterNominationFeeForInstalment:
    'Please enter nomination fee when instalments upon registration is not checked',
  pleaseEnterNominationFeeForPerMatch:
    'A nomination fee needs to be specified as a fee needs to be charged at registration in order to capture credit card details',
  duplicateFamilyDiscountError:
    'Only one Family Discount Code can be set up for each membership product. Please remove the duplicate entry.',
  membershipDuplicateFamilyDiscountError:
    'Only one Family Discount Code for Membership Fee is permitted. Please remove the duplicate entry.',
  mobileLength: 'Contact number must be 10 digits',
  pleaseFillRegistration: 'Please fill the Registration Code',
  extraTimeType: 'Please select extra time type',
  pleaseSelectBetweenUmpireAndCoach: 'User must be umpire, umpire coach or both',
  pleaseSelectOrg: 'Please select organisation',
  refundAmtRequired: 'Please enter the partial amount',
  refundAmtCheck: 'Refund amount cannot be greater that actual amount.',
  refundTypeCheck: 'Please select a refund option.',
  declineReasonRequired: 'Please select the reason to decline',
  deRegisterReasonRequired: 'Please select the reason to De-register',
  answerRequired: 'Please choose an answer below',
  deRegisterChangeTypeRequired: 'Please select the Registration change type',
  organisationField: 'Organisation is required',
  pleaseSelectGradesOrPools: 'Please select Grades or Pools',
  wpwPool1Required: 'WPW pool1 is required',
  wpwPool2Required: 'WPW pool2 is required',
  wpwPool3Required: 'WPW pool3 is required',
  wpwPool4Required: 'WPW pool4 is required',
  heroImageIsRequired: 'Hero image is required',
  competitionStartEndDateIsRequired: 'Competition Start and End date is required',
  playerTypeRequired: 'Please select the player type',
  pleaseSelectPaymentMethods: 'Please select payment methods',
  pleaseSelectPaymentOption: 'Please select a payment option',
  newMembershipDuplicateError:
    'Membership product is not same as another product you have selected',
  yearIsRequired: 'Year is required',
  membershipProductIsRequired1: 'Membership Product is required',
  affiliateAddressRequiredError: 'Please input affiliate address in details',
  affiliateAddressDetailError: 'Please select a affiliate address which has a street address',
  daysRequired: 'Number of days is required',
  extendEndDateRequired: 'Extend end date is required',
  pleaseFillDivisionBeforePublishing: 'Please fill division before publishing.',
  pleaseFillFeesBeforePublishing: 'Please fill fees before publishing.',
  membershipProductsRequired: 'Membership products is required',
  membershipFeeRequired: 'Membership Fee is required',
  fromDateIsRequired: 'From date is required',
  capEndDateIsRequired: 'Cap end date is required',
  contactStateMembership:
    'Please contact your state organisation in order to set a membership cap.',
  toDateIsRequired: 'To date is required',
  membershipIsPublished: 'Membership is published',
  paymentMandatory: 'A payment method needs to be chosen to Publish Competition Fees',
  plzReviewPage: 'Please review this page and correct any errors before submitting again',
  nameisrequired: 'Name is required.',
  suburbRequired: 'Subrub is required.',
  stateRequired: 'State is required.',
  postcodeRequired: 'Postcode is required.',
  please_SelectMembership_Types: 'Please choose a Membership Type.',
  please_SelectMembership_Product: 'Please choose a Membership Product.',
  pleaseEnterMobileNumber: 'Please enter mobile number',
  memberTypeIsRequired: 'Member type is required',
  accreditationLevelUmpire: 'National accreditation level umpire is required.',
  accreditationLevelCoach: 'National accreditation level coach is required.',
  expiryDateRequire: 'Expire date is required.',
  phoneNumberRequired: 'Phone Number is required',
  teamsMustBeDifferent: 'Teams must be different',
  typeIsRequired: 'Type is required',
  nationalMembershipProductIsRequired: 'Please select National Membership Product',
  parentStateMembershipProductIsRequired: 'Please select Linked State Membership Product',
  registrationStartIsRequired: 'Please select registration start.',
  registrationEndIsRequired: 'Please select registration end.',
  pleaseEnterVariantOptionName: 'Please complete.',
  pleaseAddVariantOption: 'Please add at least one variant option.',
  selectPromotionImage: 'Please select promotion image',
  aboutUsFieldRequired: 'About us is required.',
  trainingDaysRequired: 'Training Days is required.',
  playingDaysRequired: 'Playing Days is required.',
  websiteRequired: 'Website is required.',
  minFeeRequired: 'Min Fee is required.',
  maxFeeRequired: 'Max Fee is required.',
  membershiptypeRequired: 'Competition type is required.',
  suspensionMessage: 'You cannot create a suspension for this incident',
  tribunalMessage: 'You cannot create a tribunal for this incident',
  teamRegistrationFeeTypeMessage: 'Team Registration Fee Type is Required',
  teamRegChargeTypeMessage: 'Team Registration Charge Type is Required',
  redeemExceeded: 'Cannot Exceed the Number of Games Purchased',
  expireDateMessage: 'Membership Expiry Date is Required',
  missingDrawSettingMsg: 'Note: Both divisions and rounds must be specified when hiding draws',
  cannotTransferRegoToYourself: 'Cannot transfer registration to yourself',
  cannotUseNegativeValue: 'cannot use negative value',
  selectBothDivAndRound: 'Please specify both divisions and rounds',
  borrowRuleRequired: 'Please select a borrowing rule.',
  pageEditValidateMessages: [
    'Title is required.',
    'Field is required.',
    'Value is required.',
    'Page Template is required.',
    'Page is required.',
    'Name is required.',
    'Url is required.',
  ],
  newsEditValidateMessages: [
    'Title is required.',
    'Field is required.',
    'Value is required.',
    'Category is required.',
  ],
  siteTitleIsRequired: 'Site title is required.',
  footerTitleIsRequired: 'Footer title is required.',
  footerCopyrightIsRequired: 'Footer copyright is required.',
  websiteDomainIsRequired: 'Website domain is required.',
  websiteDomainFormatMsg: `Please use a valid format containing a minimum two and maximum 63 characters. Please ensure it only contains letters from a to z, numbers from 0 to 9 or hyphen (-). A domain name mustn't consist of a hyphen (-) on the third and fourth position at the same time, or end in a hyphen.`,
  teamField: 'Team field is required',
  missingLadderSettingMsg: 'Note: Both divisions and rounds must be specified when hiding ladders',
  addShopSameTypesInTheSameState:
    'You should not be able to add types with the same name in the same state',
  createLadderSettings: 'Please create ladder settings',
  pleaseProvideReason: 'Please provide a reason.',
  pleaseUseValidAmount: 'Please use a valid amount.',
  amountCannotExceed: 'Amount cannot exceed',
  pleaseSelectAuthoriser: 'Please select an authoriser',
  minPercentageRequired: 'Minimum percentage is required',
  dueDateRequired: 'Due date is required',
  dueDateInFuture: 'Due Date must be in future',
  invalidDiscountAmount: 'invalid discount amount',
  pleaseEnterGradeName: 'Please enter grade name',
  selectDivisionsForNamingFormat: 'Please select divisions for the naming format',
  selectNamingFormat: 'Please select a naming format',
  matchOfficialRequiredMsg: 'Match Official number is required',
  editActionLog: {
    missingFields: 'Please ensure that all fields have been set.',
    time: 'Please select a time',
    type: 'Please select an event type',
    subType: 'Please select an event sub-type',
    team: 'Please select a team',
    player: 'Pleas select a player',
    position: 'Please select a position',
  },
  somethingWentWrong: 'Something went wrong',
};

export default ValidationConstants;
