export const recordAttendancePerGameUniqueId = {
  homeIcon: 'home_icon',
  matchDay: 'Match Day',
  settings: 'Settings',
  positionTracking: 'positionTracking',
  recordGoalAttempts: 'recordGoalAttempts',
  gameTimeTracking: 'gameTimeTracking',
  attendanceReport: 'ant-select w-100 ant-select-single ant-select-show-arrow',
  games: 'Games',
  save: 'ant-btn ant-btn-primary publish-button',
  competitionDetails: 'Competition Details',
  matches: 'Matches',
  actions: 'Actions ',
  addMatch: 'Add Match',
  todayDate: 'ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today',
  date: 'date',
  division: 'division',
  time: 'time',
  okButton: 'ant-picker-ok',
  type: 'type',
  selectType: 'Halves',
  homeTeam: 'home',
  selectTeam: 'ant-select-item ant-select-item-option ant-select-item-option-active',
  awayTeam: 'away',
  venue: 'venue',
  selectVenue: 'ant-select-item ant-select-item-option ant-select-item-option-active',
  round: 'round',
  selectRound: 'ant-select-item ant-select-item-option ant-select-item-option-active',
  matchDuration: 'matchDuration',
  mainBreak: 'mainBreak',
  submit: 'submit',
  search: 'Search...',
  searchButton: 'anticon anticon-search',
  selectMatch: '/matchDayMatchDetails',
  statisticsToggle: 'switch',
  borrowPlayerButton: '+ Borrow player',
  searchPlayerInput: 'ant-select-selection-search-input',
  saveButton: 'Save',
  attendanceCheckBox: 'ant-checkbox-input',
  teamAttendance: 'Team Attendance',
  delete: 'Delete',
  yes: 'Yes',
  getStatus: 'ant-table-cell',
  player: 'ant-table-cell',
  statisticsTab: 'Statistics',
  player1: 'Player1',
  player2: 'Player2',
};
