import { RegistrationUserRoles } from 'enums/registrationEnums';

/* eslint-disable max-len */
const AppConstants = {
  deprecated: '---',
  login: 'Login',
  password: 'Password',
  addAffiliate: 'Add Affiliate',
  affiliatedTo: 'Affiliated To',
  all: 'All',
  allAllocations: 'All allocations',
  byRound: 'By Round',
  byDivision: 'By Age or Division',
  selectOneDivision: 'Please select at least one Division.',
  selectOneRound: 'Please select at least one Round.',
  selectOneRoundOrDivisioin: 'Please select at least one Division or Round.',
  organisationType: 'Organisation Type',
  status: 'Status',
  administrators: 'Administrators',
  maintain: 'Maintain',
  RegTo: 'Reg. To',
  RegFrom: 'Reg. From',
  venueAndCourts: 'Venues & Fields',
  userProfile: 'User Profile',
  myProfile: 'My Profile',
  affiliates: 'Affiliates',
  affiliateApproveReject: 'Affiliate - Approve / Reject',
  current: 'Current',
  pendingForApproval: 'Pending For Approval',
  club: 'Club',
  name: 'Name',
  address: 'Address',
  phoneNumber: 'Phone Number',
  contacts: 'Contacts',
  affiliateFinder: 'Affiliate Finder',
  aboutUs: 'About us',
  trainingDays: 'Training Days',
  playingDays: 'Playing Days',
  competitionFeeRange: 'Competition Fee Range',
  website: 'Website',
  whoCanPlayCompetition: 'Choose who can play competitions for your organisation',
  registerMembershipType: 'Choose the membership types that can register in your organisations',
  daysGroupName: 'Day',
  minMaxFeeError: 'min fee value must be less than max fee value.',
  addAnotherAvailableMember: 'Add Another Available Member',
  ourOrganisation: 'Our Organisation',
  dashboard: 'Dashboard',
  contact1: 'Contact 1',
  contact2: 'Contact 2',
  contact: 'Contact ',
  title: 'Title',
  email: 'Email',
  mobile: 'Mobile',
  permissionLevel: 'Permission Level',
  remove: 'Remove',
  addContact: 'Add Contact',
  cancel: 'Cancel',
  save: 'Save',
  association: 'Association',
  updateAffiliates: 'Update',
  add: 'Add',
  postCode: 'Postcode',
  enterPostCode: 'Enter postcode',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  unspecified: 'Unspecified',
  dob: 'Date of Birth',
  competitionInvitees: 'Competition Invitees',
  bestAndFairest: 'Best On Field',
  bestAndFairestPoints: 'Best On Field (Media Report)',
  homeTeamPlayers: 'Home Team Players',
  awayTeamPlayers: 'Away Team Players',
  allPlayersFromMatch: 'All Players from Match',
  enable: 'Enable',
  disable: 'Disable',
  whoAwardsThePoints: 'Who awards the points?',
  competitionOrganiserToAward: 'Competition Organiser to Award',
  affiliateToAward: 'Affiliate to Award',
  whoIsReceivingThePoints: 'Who is receiving the points?',
  howManyPlayersWillReceivePoints: 'How many players will receive points?',
  howManyPointsWillEachPlayerReceive: 'How many points will each player receive?',
  participant_id: 'Participant ID',
  participant_firstName: 'Participant First Name',
  participant_middleName: 'Alternative or Middle Name',
  participant_lastName: 'Participant Last Name',
  contactMobile: 'Contact Mobile',
  contactEmail: 'Contact Email',
  reenterEmail: 'Re-enter Email',
  uploadPhoto: 'Upload Photo',
  or: 'or',
  takePhoto: 'Take Photo',
  emergencyContacts: 'Emergency Contacts',
  emergencyContactName: 'Emergency Contact Name',
  emergencyContactMobile: 'Emergency Contact Mobile',
  emergencyFirstName: 'Emergency First Name',
  externalUserId: 'FA ID',
  userPhoto: 'Photo',
  emergencyLastName: 'Emergency Last Name',
  parents_guardians: 'Parent/ Guardian Details',
  firstName: 'First Name',
  lastName: 'Last Name',
  documentType: 'Document Type',
  documentUrl: 'Document Urls',
  sameAddress: 'Use same Address as Participant',
  additionalInfoReqd: 'Additional Information required',
  additionalPersonalInfoReqd: 'Additional Personal Information required',
  haveYouEverPlayed: 'Have you ever played Football before:',
  confirmTransferTo: 'Please confirm who you would like to transfer to',
  yes: 'Yes',
  no: 'No',
  loadMore: 'Load more',
  grade: 'Division',
  year: 'Year',
  clubOther: 'Club/other',
  lastCaptainName: 'Name your last Captain',
  playWithFriend: 'Play with a friend',
  referFriend: 'Refer a friend',
  friendLikeToPlay: 'Do you have a friend you think would like to play?',
  existingMedConditions: 'Existing Medical Conditions',
  regularMedicalConditions: 'Regular Medications',
  hearAboutTheCompetition: 'How did you hear about this Netball Competition?',
  who_fav_bird: 'Who is your favourite Firebird?',
  consentForPhotos: 'Do you give consent for photos to be taken and used for promotional purposes',
  favouriteTeam: 'Favourite Netball Team',
  OtherInfoReqd: 'Other information required',
  yourSupportImportant:
    'Your Support is important for the continued success of our Club. Can you help?',
  childrenNumber: 'Children Check Number',
  checkExpiryDate: 'Check Expiry Date',
  childrenCheckNumberInfo:
    'Working with Children Check Number (You are required to have a working with Children Number. If you don’t have one you will need to apply.)',
  childCountry: 'Which country were you born',
  childNationality: 'What nationality are you',
  childLangSpoken: 'Languages spoken at home',
  haveDisability: 'Do you have a disability?',
  uniformAndMerchandise: 'Uniforms and Merchandise',
  vouchers: 'Vouchers',
  addVoucher: 'Add voucher',
  agreeTerm: 'I have read and agree to the  ',
  termsAndConditions: 'Terms and Conditions',
  stateTermsAndConditions: 'Admin Terms and Conditions',
  termsAndConditionsLinkOfWorldSportAction: 'https://worldsportaction.com/terms-and-conditions',
  reviewOrder: 'Review Order',
  checkOptions: 'Checkout Options',
  voucherLink: 'Voucher link',
  photo: 'Photo',
  addParent_guardian: 'Add Parent/Guardian',
  addFriend: 'Add Friend',
  usernamePasswordIncorrect: 'Login Unsuccessful. Incorrect Username or Password',
  home: 'Home',
  user: 'User',
  externalRegistrations: 'Football Australia Registrations',
  registration: 'Registration',
  competitions: 'Competitions',
  liveScores: 'Live Scores',
  shop: 'Shop',
  umpires: 'Referees',
  incidents: 'Incidents',
  suspensions: 'Suspensions',
  tribunals: 'Tribunals',
  finance: 'Finance',
  totalRegistrations: 'Total Registrations',
  totalUsers: 'Total Users',
  edit: 'Edit',
  familyDiscount: 'Family Discount',
  appRegoForm: 'App Rego Form',
  competition: 'Competition',
  division: 'Age Group',
  saveDraft: 'Save Draft',
  next: 'Next',
  participateInComp: 'Participating-In Competitions',
  ownedCompetitions: 'Owned Competitions',
  addCompetition: 'Add Competition',
  replicateCompetition: 'Replicate Competition',
  draws: 'Draws',
  venue: 'Venue',
  round: 'Round',
  saveAsDraft: 'Save as Draft',
  publish: 'Publish',
  registrationForm: 'Registration Form',
  quickCompetition: 'Fixture Grid',
  quickCompetition1: 'Fixture Grid (1/3)',
  quickCompetition2: 'Teams & Players (2/3)',
  quickCompetitionFormat: 'Competition Format (3/3)',
  proposedTeamGrading: 'Proposed Team Grading',
  proposedGrade: 'Proposed Division',
  finalisedGrade: 'Final Division',
  comments: 'Comments',
  ladder: 'Ladder',
  competitionFormat: 'Competition Format',
  membershipProduct: 'Membership Product',
  membershipProductName: 'Membership Product Name',
  validity: 'Validity',
  membershipTypes: 'Membership Types',
  membershipType: 'Membership Type',
  playerHeading: 'Player',
  witnesses: 'Witnesses',
  offences: 'Offences',
  clarifyingQuestions: 'Clarifying Questions',
  foul: 'Foul',
  foulPlayerName: 'Foul Player Name',
  foulPlayerRole: 'Foul Player Role',
  personal: 'Personal',
  pf: 'PF',
  technical: 'Technical',
  unsportsmanlike: 'Unsportsmanlike',
  disqualifying: 'Disqualifying',
  suspendedFrom: 'Suspended From',
  suspendedTo: 'Suspended Till',
  team: 'Team',
  umpire: 'Referee',
  defaultUmpireAvailability:
    'Default Referee Availability (i.e when Referee has not set availability)',
  umpireAbbreviated: 'R',
  atCourts: 'At fields',
  coach: 'Coach',
  addMembershipType: 'Add Membership Type',
  membershipFees: 'Governing Body Fees',
  type: 'Type',
  fees: 'Fees',
  umpireFees: 'Referee Fees',
  discount: 'Discount',
  discounts: 'Discounts',
  generalDiscount: 'General Discount',
  percentageOff: 'Percentage off',
  amount: 'Amount',
  description: 'Description',
  availableFrom: 'Available From',
  availableTo: 'Available To',
  discountCode: 'Discount Code',
  code: 'Code',
  earlyDiscount: 'Early Discount',
  addChild: 'Add Child',
  addDocument: 'Add Document',
  point1: '1 Point',
  point2: '2 Points',
  point3: '3 Points',
  child1: 'Child 1 %',
  child2: 'Child 2 %',
  delete: 'Delete',
  year2019: '2019',
  timeSlot: 'Time Slots',
  timeBetweenMatches: 'Time between matches',
  divisionStartDate: 'Age Group StartDate',
  mins: 'mins',
  save_publish: 'Save & Publish',
  back: 'Back',
  finals: 'Finals',
  useDefault: ' Use Default',
  matchType: 'Match Type',
  duration: 'Duration',
  matchDuration: 'Match Duration',
  mainBreak: 'Main Break',
  quarterBreak: 'Quarter Break',
  qtrBreak: 'Qtr Break',
  betweenGames: 'Between Games',
  regenerateDraw: 'Regenerate',
  saveDraw: 'Save Draws',
  extraTimeDuration: 'Extra Time Duration',
  extraTimeMainBreak: 'Extra Time Main Break',
  extraTimeBreak: 'Extra Time Break',
  beforeExtraTime: 'Before Extra Time',
  extraTimeIfDraw2: 'Extra time if a Draw - 2nd Time',
  winByOneGoal: 'Win by one Goal',
  winByTwoGoals: 'Win by two Goals',
  addAnotherFinalFormat: 'Add Another Finals Format',
  setAsDefault: 'Set as Default',
  applyFinalFormat: 'Apply Final Format',
  fixtures: 'Fixtures',
  add_TimeSlot: 'Add Timeslot',
  addCourt: 'Add Field',
  RegistrationRestrictionType: 'RegistrationRestrictionType',
  CompetitionRegistration: 'Competition Registration',
  newCompetition_name: 'Competition Name you are Transferring to?',
  use_default_competitionFormat: 'Use default Competition Format Settings',
  fixture_template: 'Fixture Template',
  frequency: 'Frequency',
  timeBetweenRounds: 'Time between Rounds',
  days: 'days',
  hours: 'hours',
  applyMatchFormat: 'Apply Match Format to',
  setUpFinalTemplate_optional: 'Set Up Finals Template (Optional)',
  addNewCompetitionFormat: 'Add New Competition Format',
  createDraftDraw: 'Create Draft Draw',
  addNewLadderScheme: 'Add New Ladder Format',
  ladderAdjustment: 'Ladder Adjustment',
  addNewAdjustment: 'Add new Adjustment',
  recalculateLadder: 'Recalculate Ladder',
  finalise: 'Finalise',
  saveScoresAsFinals: 'Save Scores as Final',
  ladderFormatScheme: 'Ladder Point Scheme Name',
  matchSheets: 'Match Sheets',
  teams: 'Teams',
  periods: 'Periods',
  minutes: 'Minutes',
  totalGames: 'Games',
  positionTracking: 'Position Tracking / Starting Formation',
  preview: 'Preview',
  previews: 'Previews',
  printProcessing: 'Processing Downloads, Please click refresh after a short while',
  competitionDetails: 'Competition Details',
  competitionLogo: 'Competition Logo',
  addShortNotes_registering: 'Write a brief description of the Competition..',
  addVenue: ' Add Venue',
  typeOfCompetition: 'Type of Competition',
  numberOfRounds: 'Number of Rounds',
  enhancedRoundRobinType: 'Enhanced Round Robin Type',
  registrationClose: 'Registrations Close',
  registrationType: 'Registration Type',
  nonPlayingDates: 'Non-Playing Dates',
  addAnotherNonPlayingDate: 'Add Another Non Playing Date',
  addAnotherDivision: 'Add Another Age Group',
  ageRestrictions: 'Age Restrictions',
  mandateAgeRestrictions: 'Mandate Age Restrictions',
  netSetGo: 'MiniRoos Kick-off',
  dobFrom: 'DOB From',
  dobTo: 'DOB To',
  playerInEachTeam: 'Players in each team',
  minNumber: 'Minimum Number',
  maxNumber: 'Maximum Number',
  registrationInvitees: 'Registration Invitees',
  direct: 'Direct',
  percentageOff_FixedAmount: 'Percentage off or Fixed Amount',
  governmentVouchers: 'Government Vouchers',
  minPlayersTeam: 'Min. players/Team',
  numberOfTeams: '# Teams',
  extraPlayers: 'Extra Players',
  playerGradingToggle: 'Player Grading Toggle',
  playerGrading: 'Player Grading',
  open: 'Open',
  submit: 'Submit',
  final: 'Final',
  addDivisions: 'Add Age Groups',
  addTeams: 'Add Teams',
  winter_2019: 'Winter 2019',
  how_Add_teams_players: 'How will you add teams and players?',
  SetUP_Template_Optional: 'Set Up Finals Template (Optional) >',
  re_grading: 'Re-grading',
  step1: 'Step-1',
  step2: 'Step-2',
  finalisedDraw: 'Finalised Draw',
  confirm: 'Confirm',
  replicateWhichCompetition: 'Replicate which competition',
  year2018: '2018',
  competitionType: 'Competition Type',
  startDate: 'Start Date',
  registrationFees: 'Registration Fees',
  divisions: 'Age Groups',
  grades: 'Divisions',
  divisionAge: 'Age Group',
  divisionGrade: 'Age Group Division',
  div: 'Age',
  review: 'Review',
  Step_3: 'Step 3',
  contactNumber: 'Contact Number',
  addAnotherCourt: 'Add another field',
  addAnotherVenue: 'Add another venue',
  venueAndTimes: 'Venue And Times',
  game_Days: 'Game Day(s)',
  dayOfTheWeek: 'Day of the week',
  startTime: 'Start Time',
  endTime: 'End Time',
  addAnotherDay: 'Add Day',
  courts: 'Fields',
  applyTo: 'Apply to',
  addAnother: 'Add another',
  inbox: 'Actionbox',
  viewAll: 'View All',
  competitionsOverview: 'Competitions Overview',
  addNew: 'Add New',
  participatingInCompetitions: 'Participating In Competitions',
  playerProfile: 'Player Profile',
  dateOfBirth: 'Date of Birth',
  activity: 'Activity',
  statistics: 'Statistics',
  personalDetails: 'Personal Details',
  medical: 'Medical',
  username: 'Username',
  products: 'Products',
  productDetails: 'Product Details',
  playingMember: 'Playing Member',
  nonPlayingMember: 'Non Playing Member',
  category: 'Category',
  applicableTo: 'Applicable to',
  level1_Affiliate_Associations: '1st level Affiliate - Associations',
  rename: 'Rename',
  Level2_Affiliate_Clubs: '2nd Level Affiliate - Clubs',
  paymentFrequency: 'Payment Frequency',
  oncePerYear: 'Once Per Year',
  eachMatch: 'Each Match',
  eachCompetition: 'Each Competition',
  enterShortDescription: 'Enter a short description of the product...',
  dob__From: 'DOB - From',
  dob__To: 'DOB - To',
  addGst10: 'Add GST (10%)',
  clubFees: 'Club Fees',
  associationFees: 'Association Fees',
  stateFees: 'Member Federation Fees',
  allFees: 'All Fees',
  addAnotherVoucher: 'Add Another Voucher',
  addMembershipProduct: 'Add Membership Product',
  addAFee: 'Add a Fee',
  competitionFees: 'Fees',
  please_Sel_mem_pro: 'Please select membership product',
  addDivision: 'Add Age Group',
  perDivision: 'Per Age Group',
  paymentOptions: 'Payment Options',
  organisationName: 'Organisation Name',
  newOrganisationName: 'Organisation Name you are Transferring to?',
  organisationLogo: 'Organisation Logo',
  registrationOpen: 'Registration Open',
  lockRegistrationsImmediately: 'Lock Registrations Immediately',
  endUserRegistrationUrl:
    'End User Registration URL (Only Membership Types marked for public display)',
  hiddenEndUserRegistrationUrl: 'End User Registration URL (Only Hidden Membership Types)',
  training: 'Training',
  trainingVenue: 'Training Venue',
  specialNote: 'Special Note',
  replyToContactDetails: 'Reply to contact details',
  role: 'Role',
  phone: 'Phone',
  how_users_Register: 'How Users Register',
  app: 'App',
  advancedSettings: 'Advanced Settings',
  disclaimers: 'Disclaimers',
  disclaimerLink: 'Disclaimer Link',
  addAnotherDisclaimerLink: 'Add Another Disclaimer Link',
  openRegistrations: 'Open Registrations',
  product: 'Product',
  dOB: 'DOB',
  year2020: '2020',
  year2017: '2017',
  year2016: '2016',
  registrationAccountSummary: 'Registration Account Summary',
  paymentFor: 'Payment For',
  dateFrom: 'Date From ',
  dateTo: 'Date To',
  umpireAllocation: 'Referee Allocation',
  users: 'Users',
  ages: 'Ages',
  roles: 'Roles',
  genders: 'Genders',
  alternate_location: 'Alternative location (within 25km)',
  other: 'Other',
  participant: 'Participant',
  specialNotes: 'Special Notes',
  courtPreferences: 'Field preferences',
  details: 'Details',
  membership: 'Membership',
  payments: 'Payments',
  general: 'General',
  addDiscount: 'Add Discount',
  question: 'Question',
  select: 'Select',
  trainingDaysAndTimes: 'Training days and Times',
  matchList: 'Match List',
  addMatches: 'Add Matches',
  export: 'Export',
  import: 'Import',
  addMatch: 'Add Match',
  date: 'Date',
  divisionName: 'Age Group Name',
  matchID: 'mnbMatchId',
  homeTeam: 'Home Team',
  awayTeam: 'Away Team',
  umpire1Id: 'Referee 1 Id',
  umpire2Id: 'Assistant Referee 1 Id',
  umpire1Name: 'Referee Name',
  umpire2Name: 'Assistant Referee 1 Name',
  umpire3Name: 'Assistant Referee 2 Name',
  umpire4Name: '4th Official Name',
  enterUmpire1name: 'Enter Referee Name',
  enterUmpire2name: 'Enter Assistant Referee 1 Name',
  enterUmpire3name: 'Enter Referee Assistant Referee 2 Name',
  enterUmpire4name: 'Enter 4th Official Name',
  selectUmpire1Name: 'Select Referee Name',
  selectUmpire2Name: 'Select Assistant Referee 1 Name',
  selectUmpire3Name: 'Select Assistant Referee 2 Name',
  selectUmpire4Name: 'Select 4th Official Name',
  umpire1Club: 'Referee Organisation',
  umpire2Club: 'Assistant Referee 1 Organisation',
  umpire3Club: 'Assistant Referee 2 Organisation',
  umpire4Club: '4th Official Organisation',
  umpireCoachClub: 'Referee Assessor Organisation',
  umpireReserveClub: 'Referee Reserve Organisation',
  selectUmpire1Organisation: 'Select Referee Organisation',
  selectUmpire2Organisation: 'Select Assistant Referee 1 Organisation',
  selectUmpire3Organisation: 'Select Assistant Referee 2 Organisation',
  selectUmpire4Organisation: 'Select 4th Official Organisation',
  selectUmpireCoachOrganisation: 'Select Referee Assessor Organisation',
  selectUmpireReserveOrganisation: 'Select Referee Reserve Organisation',
  umpire1Response: 'Referee Response',
  umpire2Response: 'Assistant Referee 1 Response',
  umpire1NotAvailable: 'Referee 1 (${umpire1}) is not available now, please assign a new Referee 1',
  umpire2NotAvailable: 'Referee 2 (${umpire2}) is not available now, please assign a new Referee 2',
  umpireReserveNotAvailable:
    'Referee Reserve (${referee}) is not available now, please assign a new Referee Reserve',
  selectUmpireToAssign: 'Please select a referee to assign',
  umpireOrganisationNotFound: 'Referee organisation not found',
  scorer1: 'Scorer 1',
  scorer2: 'Scorer 2',
  umpireName: 'Referee Name',
  umpireClubName: "Referee's Organisation Name",
  scorerName: 'Scorer Name',
  score: 'Score',
  players: 'Players',
  addScorer: 'Add Scorer',
  selectTeam: 'Select Team',
  emailAdd: 'Email Address',
  enterEmail: 'Enter Email',
  contactNO: 'Contact no',
  contact_No: 'Contact No',
  enterContactNo: 'Enter Valid Contact Number',
  scorers: 'Scorers',
  addTeam: 'Add Team',
  teamName: 'Team Name',
  enterTeamName: 'Enter Team Name',
  teamLogo: 'Team Logo',
  selectCompetition: 'Select Competition',
  selectDivision: 'Select Age Group',
  managerHeading: 'Manager',
  new: 'New',
  existing: 'Existing',
  teamList: 'Team List',
  managersList: 'Manager List',
  addManager: 'Add Manager',
  importManager: 'Import Manager',
  upload: 'Upload',
  aboutManager: 'About Manager',
  managerProfile: 'Manager Profile',
  emailAddress: 'email@gmail.com',
  enterFirstName: 'Enter First Name',
  enterLastName: 'Enter Last Name',
  enterDateOfBirth: 'Enter date of birth',
  importMatch: 'Import Match',
  fileInput: 'File Input',
  importTeam: 'Import Team',
  exampleBlock: 'Example block-level help text here.',
  noImage: 'No Image',
  homeTeamFinalScore: 'Home Team Final Score',
  awayTeamFinalScore: 'Away Team Final Score',
  enterHomeTeamFinalScore: 'Enter Home Team Final Score',
  enterAwayTeamFinalScore: 'Enter Away Team Final Score',
  editMatch: 'Edit Match',
  editTeam: 'Edit Team',
  editManager: 'Edit Manager',
  editScorer: 'Edit Scorer',
  umpireList: 'Referee List',
  filterByDivision: 'Filter By Age Group',
  competitionLadders: 'Competition Ladders',
  playerList: 'Player List',
  importPlayer: 'Import Player',
  addPlayer: 'Add Player',
  editPlayer: 'Edit Player',
  profilePic: 'Profile Picture',
  enterPlayerID: 'Enter player ID',
  playerId: 'Player ID',
  shootingState: 'Shooting Stats',
  incidentDetails: 'Incident Detail',
  photos: 'Photos',
  forfeit: 'Forfeit',
  abandon: 'Abandon',
  endMatch: 'End match',
  addNews: 'Add News',
  editNews: 'Edit News',
  newsTitle: 'News Title',
  enterNewsTitle: 'Enter News Title',
  newsBody: 'News Body',
  author: 'Author',
  enterAuthor: 'Enter Author',
  recipients: 'Recipients',
  selectRecipients: 'Select Recipients',
  newsImage: 'News Image',
  newsVideo: 'News Video',
  newsExpiryDate: 'News Expiry Date',
  newsExpiryTime: 'News Expiry Time',
  newsDetail: 'News Detail',
  settings: 'Settings',
  venues: 'Venues',
  wouldLikeRecord: 'Would you like to record?',
  record: 'Record',
  report: 'Report',
  attendance_record_report: 'Attendance Recording and Reporting',
  scoring: 'Scoring',
  whoScoring: 'Who scoring',
  managersToScore: 'Managers to assign scorer',
  courtToScope: 'Field to score',
  acceptScores: 'Accept scores',
  umpireAcceptScores: 'Referee to Accept Scores',
  scorerAcceptScores: 'Scorer to Accept Scores',
  single: 'Single',
  timer: 'Timer',
  ladderSettings: 'Ladder Settings',
  publish_notify: 'Publish and Notify',
  backToNews: 'Back to all news',
  scorerHeading: 'Scorer',
  banners: 'Banners',
  uploadImage: 'Upload Image',
  bannerLink: 'Banner Link',
  horizontalBannerLink: 'Horizontal Banner Link',
  squareBannerLink: 'Square Banner Link',
  sponsorName: 'Sponsor Name',
  numberOfAdvertisingBanners: 'Number of Advertising Banners',
  stateBody: 'State Body',
  competitionOrganiser: 'Competition Organiser',
  removeBanner: 'Remove Banner',
  showHomePage: 'Show On Home Page',
  showOnDrawsPage: 'Show On Draws Page',
  showOnLadderPage: 'Show On Ladder Page',
  showOnNewsPage: 'Show On News Page',
  showOnChatPage: 'Show On Chat Page',
  bannerFormat: 'Banner Format',
  teamAttendance: 'Team Attendance',
  newsList: 'News List',
  goalState: 'Goal Statistics',
  bulkMatchChange: 'Bulk Match Change',
  whatDoWantDO: 'What do you want to do?',
  selectOption: 'Select Option',
  whichMatchChange: 'Which matches do you want to change?',
  matchOnDate: 'Matches on this date',
  forTimeRange: 'For this time range',
  byVenue: 'By Venue (optional)',
  hour: 'Hours',
  seconds: 'Seconds',
  toThisTime: 'Or to this time',
  pushBack: 'Push Back',
  court: 'Field',
  selectCourt: 'Select Field',
  selectGrade: 'Select Division',
  pleaseSelectCourtId: 'Please select field id',
  round_1: 'Round 1',
  round_2: 'Round 2',
  selectRoundOne: 'Select Round 1',
  bringForward: 'Bring forward',
  changeMatchCriteria: 'Change matches with the following criteria',
  selectReason: 'Select Reason',
  affiliate: 'Affiliate',
  selectAffiliate: 'Select Affiliate',
  useClubLogo: 'Use Affiliate Logo',
  activeNews: 'Active News',
  addNewRound: 'Add New Round',
  editBanners: 'Edit Banners',
  editBanner: 'Edit Banner',
  addBanners: 'Add Banners',
  exportUrl: '/players/csv?',
  membershipTypeName: 'Membership Type Name',
  pleaseEnterMembershipTypeName: 'Please Enter Membership Type Name',
  anyGradePreference: 'Do you have any field preferences for age groups or divisions?',
  saveAsDefault: 'Save as Default',
  anyTimePreference: 'Do you have any timeslot preferences for age groups or divisions?',
  none: 'None',
  newCompetition: 'New Competition',
  teamPreferences: 'Team Preferences',
  teamGradingSummary: 'Team Grading Summary',
  addGrade: 'Add Division',
  linkToHomeAffiliate: 'Link To Home Affiliate',
  addressOne: 'Address Line 1',
  addressTwo: 'Address Line 2',
  suburb: 'Suburb',
  postcode: 'Postcode',
  selectVenue: 'Select Venue',
  managerSearch: 'Manager Search',
  scorerSearch: 'Scorer Search',
  organisationTypeRefId: 'organisationTypeRefId',
  affiliatedToOrgId: 'affiliatedToOrgId',
  stripeCustomerAccountId: 'Stripe Customer ID',
  middleName: 'Middle Name',
  finalTeamGrading: 'Final Team Grading',
  updateGradeName: 'Update Division Name',
  gradeName: 'Division Name',
  pleaseEnterGradeName: 'Please enter division name',
  todaysIncidents: "Today's Incidents",
  todaysMatch: "Today's Matches",
  recipientSelection: 'Select Recipients',
  ByMatch: 'By Match',
  total: 'Total',
  areYouRegisteringYourself: 'Are you registering yourself?',
  whoAreYouRegistering: 'Who are you registering?',
  child: 'Child',
  whatTypeOfRegistration: 'What type of registration?',
  nonPlayer: 'Non Player',
  yesAsAPlayer: 'Yes, as a Player',
  yesAsANonPlayer: 'Yes, as a Non-Player',
  registeringSomeoneElse: 'No, Registering someone else',
  competitionMembershipProductDivision: 'Competition, Membership Product and Age Group',
  participantDetails: 'Participant Details',
  indicatePreferredPlayerPosition: 'Indicate two preferred playing positions:',
  fullName: 'Full Name',
  playWithFriendSubtitle:
    'We may be able to accommodate friends playing with each other. Please note, this is normally only available for lower graded teams. You can choose up to three friends.',
  addAnotherProduct: 'ADD ANOTHER PRODUCT',
  addAnotherParticipant: 'ADD ANOTHER PARTICIPANT',
  organisation: 'Organisation',
  favouriteTeamReference: 'FavouriteTeam',
  firebirdPlayer: 'FirebirdPlayer',
  registrationOtherInfo: 'RegistrationOtherInfo',
  countryReference: 'Country',
  nationalityReference: 'Nationality',
  heardByReference: 'HeardBy',
  playerPosition: 'PlayerPosition',
  position1: 'Position 1',
  position2: 'Position 2',
  venuesList: 'Venue List',
  venueDeleteConfirm: 'Are you sure you want to delete this venue?',
  enhancedRoundRobin: 'EnhancedRoundRobin',
  createTeam: 'Create Team',
  unassigned: 'Unassigned',
  gameTimeStatistics: 'Game Time Statistics',
  searchManager: 'Search Manager',
  searchScorer: 'Search Scorer',
  divisionList: 'Age Group List',
  notifyAgain: 'Notify again',
  notify: 'Notify',
  editDivision: 'Edit Age Group',
  national: 'national',
  state: 'state',
  super_admin: 'super_admin',
  admin: 'admin',
  manager: 'Manager',
  scorer: 'scorer',
  member: 'member',
  spectator: 'spectator',
  attendance_recorder: 'attendance_recorder',
  player: 'player',
  parent: 'parent',
  parentHeading: 'Parent',
  web_communications_admin: 'web_communications_admin',
  web_umpires_admin: 'web_umpires_admin',
  web_results_admin: 'web_results_admin',
  web_finance_admin: 'web_finance_admin',
  period: 'PERIOD',
  minute: 'MINUTE',
  matches: 'MATCH',
  totalGame: 'TOTAL GAMES',
  voucherDeleteConfirmMsg: 'Are you sure you want to delete this voucher?',
  productDeleteConfirmMsg: 'Are you sure you want to delete this product?',
  participantDeleteConfirmMsg: 'Are you sure you want to delete this participant?',
  friendDeleteConfirmMsg: 'Are you sure you want to delete this friend?',
  pleaseEnterTeamName: 'Please Enter Team Name',
  selectPlayer: 'Select Player',
  claim: 'Claim',
  yesNo: 'Yes/No',
  playerConst: 'Player',
  addImages: 'Add Images',
  addVideos: 'Add Video',
  time: 'Time',
  sinBin: 'Sin bin',
  includeInPersonalFouls: 'Include in Personal Fouls',
  addIncident: 'Add Incident',
  sendoffReport: 'Sendoff report',
  addSendoffReport: 'Add Sendoff Report',
  selectRound: 'Select Round',
  linked: 'Linked',
  importDivision: 'Import Age Group',
  assignMatches: 'Assign Matches',
  venueChange: 'Venue Change',
  importIncident: 'Import Incident',
  endDate: 'End Date',
  please_Sel_Fee: 'Please complete fees on the previous tab',
  short_Name: 'Short Name',
  backToScorer: 'Back to all Scorers',
  otherInformation: 'Other Information',
  countryOfBirth: 'Country of Birth',
  disability: 'Disability',
  additionalQuestions: 'Additional Questions',
  otherQuestions: 'Other Football Questions',
  netballQuestions: 'Football Questions',
  demographicQuestions: 'Demographic Questions',
  addDivisionsAndGrades: 'Add Age Groups and Divisions',
  useAffiliateLogo: 'Use Affiliate logo',
  add_edit_comment: 'Add/Edit Comment',
  addYourComment: 'Please add your comment.',
  fixedDuration: 'Fixed Duration',
  specificTime: 'Specific Time',
  selectOrganisation: 'Select Organisation',
  goalExport: '/stats/export/scoringByPlayer?competitionId=',
  gameTimeExport: '/stats/export/gametime?competitionId=',
  teamAttendanceExport: '/players/export/teamattendance?competitionId=',
  bestAndFairestExport: '/bestAndFairest/export/points?competitionId=',
  proceed: 'Skip and Proceed',
  invalidPlayers: 'Invalid Records',
  matchExport: '/matches/export?competitionId=',
  courtChange: 'Field Change',
  totalCompetitions: 'Total Competitions',
  toEditRegistrationDetails: 'To edit registration details, please go to',
  registrationArea: 'registration area',
  logoImageSize: 'Selected file must be less then 2 MB',
  logoType: 'Selected file must be PNG, GIF or JPEG format',
  logo_size: 2000000,
  referaFriend: 'Refer a Friend',
  playWithAFriend: 'Play with a Friend',
  divisionsTimeSlot: 'Add Age Groups (in timeslot order - first to last)',
  gradesTimeSlot: 'Add Divisions (in timeslot order - first to last)',
  poolsTimeSlot: 'Add Pools (in timeslot order - first to last)',
  seasonFixture: 'Season Fixture',
  payment: 'Payment',
  firstlevelAffiliate: 'Affiliates - 1st level Affiliates - Association/Leagues',
  secondlevelAffiliate: 'Affiliates - 2nd level Affiliates - Club/ School',
  anyOrgAssociation: 'Any organisation - Association/Leagues',
  anyOrgClub: 'Any organisation - Clubs/ Schools',
  NoRegistrations: 'No Registrations',
  submitPayment: 'Submit Payment',
  connectToStripe: 'Connect to Stripe',
  exportPayments: 'Export Payments',
  exportWithdrawals: 'Export Withdrawals',
  stripePaymentDashboard: 'Stripe Payments Dashboard',
  stripeWithdrawalsDashboard: 'Stripe Withdrawals Dashboard',
  setupStripeForWithdrawals: 'Set up Stripe for Withdrawals',
  dispute_description: 'Result in dispute',
  draft_description: 'Final result entered and unconfirmed',
  final_description: 'Final result entered and confirmed',
  deleteTeam: 'Delete Team',
  addPhoto: 'Add Photo',
  editPhoto: 'Edit Photo',
  photoType: 'PhotoType',
  matchesList: 'Matches List',
  orgPhotosText: 'These photos will display on the User Registration Form',
  compStartDate: 'Competition Start Date',
  compCloseDate: 'Competition End Date',
  importTeams: 'Import Teams',
  noPhotosAvailable: 'No photos available',
  downloadTemplate: 'Download Template',
  finalsStartDate: 'Finals Start Date',
  extraTimeMatchType: 'Extra Time Type',
  applyToRef: 'ApplyToFinals',
  extraTimeDrawRef: 'ExtraTimeDraw',
  finalsFixtureTemplateRef: 'FinalsFixtureTemplate',
  allowTeamRegistrationTypeRefId: 'TeamRegistrationType',
  matchPreference: 'Match Preference',
  teamA: 'Team A',
  teamB: 'Team B',
  lockedDraws: 'Specific Match Preference',
  addDay: 'Add Day',
  backToLiveScore: 'Back To Live Score',
  venueConstraintModalMsg: 'Do you want to remove fixture?',
  removeFixture: 'Remove Fixture',
  addPreference: 'Add Preference',
  forgotResetPassword: 'Forgot/ Reset Password',
  returnToLogin: 'Return to login',
  logo: 'Logo',
  registrationFormQuestions: 'Registration Form Questions',
  noInformationProvided: 'No information provided',
  bankAccountForWithdrawals: 'Bank Account for Withdrawals',
  previous: 'Previous',
  totalPages: 'Total pages',
  currentPage: 'Current page',
  buzzer: 'Buzzer',
  extraTimeLabel: 'Extra Time',
  extraTimeCheckboxTitle: 'Extra time for a Draw in Round Matches',
  oneExtraTimeForDraw: 'Allow only one extra time for a draw',
  extraTimeForAllDraws: 'Allow extra time for all draws in this Match',
  sinBinLengthOfTimeLabel: 'Temporary Dismissal Length of Time',
  timeouts: 'Timeouts',
  applyToHalves: 'Apply to Halves',
  applyToQuarters: 'Apply to Quarters',
  turnOff_30Second: '30 second warning',
  payouts: 'Payouts',
  coachExport: '/users/byRole/export',
  managerExport: '/users/byRole/export',
  scorerExport: '/roster/exportScorer?entityTypeId=',
  positionExport: '/stats/positionTracking/export?',
  teamExport: '/teams/export?competitionId=',
  playersToPay: 'Players to Pay',
  exportTeams: 'Export Teams',
  exportPlayers: 'Export Players',
  transactions: 'Transactions',
  addCharityDescription: 'Write a brief description of the Charity..',
  addCoach: 'Add Coach',
  editCoach: 'Edit Coach',
  coachList: 'Coach List',
  noDataAvailable: 'No Data Available',
  recordUmpire: 'Allocate Referee',
  recordUmpirePlaceholder: 'Select Allocate Referee',
  deleteDivision: 'Delete Competition Age Group',
  deleteGrade: 'Delete Division',
  changeDivision: 'Change Age Group',
  action: 'Action',
  competitionDivisionValidation:
    'If there are any players graded to this age group, they will be unassigned.',
  deleteDrawsForDivision: 'Do you want to delete matches for this age group?',
  secondDeleteDivisionMessage:
    'Are you sure you want to delete this age group? You cannot undelete this age group once this has been deleted.',
  deleteDrawsForGrade: 'Do you want to delete matches for this division?',
  deleteGradeMessage: 'Do you want to delete this division?',
  secondDeleteGradeMessage:
    'Are you sure you want to delete this division? You cannot undelete this division once this has been deleted.',
  exception: 'Exception',
  exceptionHeading:
    'This allows you to schedule a match at a venue or time outside the automatic scheduling',
  LatitudeMsg: `1. Go to google maps https://www.google.com/maps\n\n'
      2. Click on satellite view.\n\n
      3. Search for your venue.\n\n
      4. Click and drop a pin on the centre of the field then copy and paste both the Longitude and Latitude.`,
  overRideSlotMsg:
    'Only click if the Field has different availability to the Venue ie. Field 1 is only available for matches from 9am but the other fields are free from 8am',
  gameDayMsg: 'Add the days of the week, matches can be played at this venue. Click + Add Day.',
  courtsMsg:
    'Add the Fields at this venue. For effective use of the Live Scoring App please add Longitude and Latitude of the Field.',
  activeNewsMsg: 'A list of all of the news that currently appears in the Game Day App',
  todayMatchMsg:
    'A list of all the matches being played on this day. This list shows whether scorers have been set, attendance has been taken and if umpires have been recorded(optional). Please refresh your screen to get the latest updates.',
  playersToPayMsg:
    'A list of Players who have registered and are required to pay either with cash or a voucher.',
  todayIncidentMsg:
    'If enabled, a list of all of the incidents that have occurred on this day including injuries and disciplinary.',
  matchDurationMsg: 'Game time only (in minutes). This time should exclude time for breaks.',
  mainBreakMsg: 'Half time break (in minutes).',
  qtrBreatMsg: 'Break after 1st and 3rd quarters (in minutes).',
  teamAliasMsg: 'The name that is used for the Team on the draw and media.',
  bulkMatchMsg: `Push Back - Push back one, a number or all games to a day or time that suits.\n\n
      Bring Forward - Bring forward one, a number or all games to a day or time that suits.\n\n
      Abandon Matches - Abandon one, a number or all matches that are incomplete or not played.\n\n
      End Matches - End one, a number or all matches.\n\n
      Double Header - Create a double header where two rounds are played in the one round allocation ie. Round 2 is rained out and the association decides to play Round 2 and Round 3 together as two half matches.`,
  courtChangeMsg: 'Move the matches on one, many or all Venues, Fields to another Venue, Field.',
  shortNameMsg: 'The short name is used in the APP to make it easier for users to search.',
  enhancedRoundRobinTypeMsg:
    'Based on the ranking of teams the draw will generate as either 1st ranked Vs 2nd ranked or 1st ranked vs last ranked.',
  extraTimeIfDraw2Msg:
    'If Extra Extra time is being played. Does the 1st Goal win or Does the team need to score 2 Consecutive Goals.',
  ladderCalculationTypeMsg: `Goal Average = Total score for / total goals against.\n\n
      SMR % = (Total score for / total goals against) /  number of games played.\n\n
      Win % = Number of games won / Number of games played.`,
  attendanceRecordingTimeMsg:
    'The amount of time before Managers, Coaches and Scorers can submit team attendance.',
  recordUmpireMsg:
    'The Scorer or Manager of a match will document the Referee names and the Clubs they belong to.',
  positionTrackMsg: 'If Selected allows tracking of team positions by player.',
  recordMsg:
    'Choose between allowing scorers to record their own team, both teams or the oppositions team attendance.',
  reportMsg:
    'Determine which game time report you would like managers and coaches to see - choose between minute, period or games.',
  buzzerMsg: `Click on Turn off the Buzzer so it doesnt signal the start, breaks or end of the game.\n\n
      Click on 30 second warning so it doesnt sound with a 30 second warning for players to take the field.`,
  newsPublishMsg: 'Publish the news/ message to the App only.',
  newsPublishNotifyMsg: 'Publish the news/ message to the App and notify App users.',
  participateCompMsg: 'A list of all Competitions your Organisation is competing in.',
  ownedCompetitionMsg: 'A List of all Competitions your Organisation is responsible for.',
  compDetailsMsg:
    'If you have opened Registrations for this Competition, then Competition Details fields will be pre-populated but you can change key details as appropriate. If you have not opened Registrations for this competition, then you need to complete these screens.',
  knockOutMsg:
    'A competition where teams are eliminated progressively. Each winner will play another in the next round until the final two teams meet.',
  roundRobinMsg: 'Teams play each other one time. Finals are optional.',
  enhancedRoundRobinMsg:
    'Teams play each as many times as required in the number of rounds specified. Finals are optional.',
  compDivisionMsg:
    'You must add a Age Group to move to the next screen. The choice of Age Groups is up to you. They could be MiniRoos, U10, U14 or AA as examples.',
  genderRestrictionMsg:
    'Restricts Users who register to a particular age group based on their gender.',
  ageRestrictionMsg: 'Restricts Users who register to a particular age group based on their DOB.',
  playerGradingMsg:
    'For Direct Competitions only. Create Teams and then Drag and Drop Players from Unassigned in to their teams.',
  playerGradingToggleMsg:
    'Displays a running tally of the number of teams required for each age group and the number of players in each team.',
  teamGradingSummaryMsg:
    "Teams will remain ungraded until you move them into Divisions. Click on the square titled 'Unassigned' (which contains the number of teams) to begin grading.You can also re-name divisions by clicking on the letter or name.",
  timeSlotNoPrefMsg:
    'There is no preference for the timeslots Age Groups, Divisions and Teams play in.',
  timeSlotEvenRotationMsg: 'Age Groups, Divisions and Teams equally rotate through the timeslots.',
  allocateToSameTimeslotMsg: 'Age Groups and Divisions can be allocated to a Timeslot.',
  affiliateDirectory: 'Affiliate Directory',
  evenRotationMsgFor_V_T: 'Evenly rotate Age Groups or Divisions to Fields.',
  allocateToSameCourtMsg: 'Allocate Age Groups or Divisions to the same fields.',
  noPreferenceMsgFor_V_T: 'There is No Preference for Field Rotations or Allocations',
  newTeamUserMsg:
    'Add a user who has NOT created an account in the App, is an administrator or has registered.',
  existingTeamUserMsg:
    'Add a user who has either created an account in the App, is an administrator or has registered.',
  doubleRoundRobinMsg: 'Teams play each other twice. Finals are optional.',
  timeSlote_BasedOnMatchDurationMsg: 'Timeslots are determined based on the match duration.',
  manuallyAddTimeSloteMsg:
    'Manually create Timeslots. You can apply these timeslots to all or individual Venues.',
  equallyRotateHomeAwayMsg:
    'Choose Equally rotate teams home/away venue competition if competition features Home and Away venues.',
  equallyRotateCentralizedVenueMsg:
    'Choose Equally rotate teams - centralised venue competition if competition is run at centralised venues.',
  regInviteesAffiliatesMsg:
    'Organisations that are affiliated below your organisation. They will invite Users (Players, Coaches, Referees etc) to register to their organisation and they will then submit them to your competition.',
  regInviteesAnyOrgMsg:
    'Add Organisation(s) not linked below your organisation in your State.They will invite Users (Players, Coaches, Referees etc) to register to their organisation and they will then submit them to your competition.',
  regInviteesDirectMsg:
    'Users (Players, Coaches, Referee etc) will register direct to your organisation and you will place them into teams (if they are not directly registering teams to your organisation).',
  regFormDashBoardMsg:
    'After you have added your Competition Fees, locate the Competition in the Registration Form table and click on edit (three dots in Action) to add Registration details and open registrations.',
  regFormOpenMsg: 'List the date you want Registrations to open and be made available to users.',
  regFormCloseMsg:
    'List the date you want Registrations to close. Please note registrations can still be taken after this date if required.',
  regLockMsg:
    'Registration Lock immediately closes registration for those age groups it is applied to.',
  regFormTrainingMsg: 'Show users training details like Date, Time and Venue.',
  regFormSpecialNoteMsg:
    'Detail any special notes you would like to include on the Registration Form.',
  regFormPhotoMsg:
    'These are stored in "Our Organisation" Photos. You can display as many photos as you would like to Users to show them your uniform, fields, logo etc.',
  replyContactDetailMsg:
    'Let Users know who to contact if they have any questions. You can choose to list their Name, Role, Email and or Phone number.',
  howUserRegisterMsg: 'Define how Users can Register for your Competition.',
  additionQuesMsg:
    'Click on the Questions you would like to ask Users who are Registering to your Competition.',
  allDivisionsMsg: 'All Age Groups are charged the same Fees.',
  perDivisionMsg: 'Each Age Group can be charged a different Fee. ',
  paymentSeasonalFeeMsg:
    'Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.',
  paymentCausalFeeMsg:
    'Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.',
  charityRoundUpMsg:
    'Add the ability for users Registering to round up their registration to the nearest $1, $5 or $10 to support the pre-defined charity.',
  discountMsg:
    'Choose the discount you would like to apply to your Competition Fee. Please note, this discount only applies to your organisations Competition Fee. You can choose which membership Product and Type this fee is applied to.',
  membershipProductNameMsg:
    'Add a name that your affiliated organisations can resonate with e.g. Annual Membership Fee',
  validityMsg: `Add how long you want the membership product to be available:\n\n
      * Calendar Year - 1st Jan to 31st Dec in that year\n\n
      * 12 months from date of Registration`,
  membershipCasualFeeMsg: 'Fee charged to participate in a single game.',
  membershipSeasonalFeeMsg: 'Fee charged to join a Football competition.',
  firstComRegOnlyMsg:
    'Fee charged to the User for the first competition they join in the defined period (whether it be calendar year or 12 months from date of registration). It will not be charged if they join another competition in that defined period.',
  allCompRegMsg:
    'Fee charged to the User every time they join a competition in the defined period (whether it be calendar year or 12 months from date of registration).',
  orgTypeMsg:
    'Detail the type of organisation being added. State Organisations can add Associations/ Leagues and Clubs/ Schools, Associations can only add Clubs/ Schools.',
  addAffiliatePermissionLevelMsg: `Choose the permission level for each contact.\n\n
      Admin - can access all areas in the platform.\n\n
      Referees Admin - can access the Referees platform.\n\n
      Finance Admin - can access Payments and the Registration platform.`,
  ourOrgPermissionLevelMsg: `Choose the permission level for each contact.\n\n
      Admin - can access all areas in the platform.\n\n
      Referees Admin - can access the Referees platform.\n\n
      Finance Admin - can access Payments and the Registration platform.`,
  importCoach: 'Import Coaches',
  ladderLink: 'Ladder Link',
  inviteTypeRef: 'InviteType',
  inviteType: 'Type',
  DobMoreThan: 'DOB more than',
  DobLessThan: 'DOB less than',
  NoDobPreference: 'No DOB Preference',
  DobPreference: 'DOB Preference',
  both: 'Both',
  sendInvitesTo: 'Send invites to',
  registrationWizard: 'Registration Wizard',
  createPublish: 'Create and Publish',
  set: 'Set',
  setup: 'Set up',
  setupStripe: 'Stripe account',
  resultStatus: 'Result Status',
  whichTeamForfeited: 'Which team forfeited?',
  matchAbandoned: 'Match Abandoned?',
  addUmpire: 'Add Referee',
  editUmpire: 'Edit Referee',
  umpireSearch: 'Referee Search',
  nonPlayerDivisionMessage: 'Age Groups are not required for your selected membership type.',
  drawsLink: 'Draws Link',
  finalsMessage: 'Finals has not been enabled for this Competition',
  allowTeamRegistration: 'Allow Team Registrations',
  individualRegistrations: 'Individual User Registrations',
  importUmpire: 'Import Referee',
  addAProduct: 'Add a Product',
  enterTitle: 'Enter Title',
  pricing: 'Pricing',
  price: 'Price',
  costPerItem: 'Cost per item',
  chargeTaxesOnProduct: 'Charge taxes on product',
  inventory: 'Inventory',
  enableInventoryTracking: 'Enable inventory tracking',
  StockKeepingUnit: 'Stock keeping unit',
  skuHeader: 'SKU(stock keeping unit)',
  barcodeHeading: 'Barcode(ISBN, UPC, GTIN etc)',
  barcode: 'Barcode',
  quantity: 'Quantity',
  allowCustomerToPurchase: "Allow customers to purchase this product when it's out of stock",
  variants: 'Variants',
  enableVariants: 'Enable Variants',
  variantName: 'Variant Name',
  variant_name: 'Variant name',
  orders: 'Orders',
  orderSummary: 'Order Summary',
  orderStatus: 'Order Status',
  parentOrGuardianDetail: 'Parent/Guardian Details',
  useChildEmail: 'Same as child’s email',
  useParentEmail: 'Use parent’s email address',
  childMsg2Parent:
    'You have elected to use the same email for your Child and yourself. You child will not get their own log-in. If you would like them to have their own log-in please give them a separate email address.',
  childMsg2Admin:
    'You have elected to use the same email for the Child and Parent. The child will not get their own log-in. If you would like them to have their own log-in please give them a separate email address.',
  parentMsg2Child:
    'You have elected to use the same email for your Parent and yourself. You will lose your login unless you update your own email address first.',
  parentMsg2Admin:
    'You have elected to use the same email for the Child and Parent. The child will not retain their own login. If you would like them to have their own login please give them a separate email address first.',
  valueOfOrders: 'Value of ORDERS',
  orderId: 'Order Id',
  netProfit: 'Net Profit',
  paid: 'Paid',
  paymentStatus: 'Payment Status',
  fulfilmentStatus: 'Fulfilment Status',
  attendanceRecordingTime: 'Attendance Recording Time',
  _days: 'Days',
  _hours: 'Hours',
  _minutes: 'Minutes',
  lineUpSelectionMsg: 'We can’t enable lineup selection without position tracking',
  umpireListExport: 'users/byRole/export/org?',
  disabilityCareNumber: 'Disability care Number',
  typeOfDisability: 'Type of Disability',
  pickUpAddress: 'Pick up address',
  productTypes: 'Product Types',
  topSellers: 'Top Sellers',
  productType: 'Product Type',
  divisionGradeAndTeams: 'Age Group, Division and Teams',
  numbersOfTeams: 'Number of teams',
  shipping: 'Shipping',
  pickup: 'Pickup',
  pickupInstructions: 'Pick Up Instructions',
  productDimensionsWeight: 'Product dimensions and weight',
  dimensions: 'Dimensions',
  sku: 'SKU',
  option: 'Option',
  addVariantOption: 'Add variant option',
  deleteProduct: 'Delete Product',
  deleteProductDescription: 'Please confirm you want to delete this product?',
  umpireDashboardExport: '/matchUmpire/dashboard/export?',
  umpirePayoutsExport: '/matchUmpire/payouts/export?',
  updateAction: 'Update Action',
  actionBoxConfirmMsg: 'Are you sure you want to complete this activity?',
  backToUmpire: 'Back to all Referees',
  assignMatch: 'Assign Match',
  howUmpiresAllocated: 'How are Referees Allocated',
  umpireReservePref: 'Referee Reserve',
  activeUmpireCoach: 'Activate Referee Assessors',
  umpirePoolsDivision: 'Referee Panels Allocation To Age Groups/Divisions',
  allocateUmpires: 'Allocate Referees',
  noPoolAdded: 'Panels were not added to this competition yet.',
  poolsDisabled: 'Panels are not enabled for this competition',
  umpireCoach: 'Referee Assessor',
  umpirePool: 'Referee Panel',
  umpirePools: 'Referee Panels',
  competitionVenueAllocation: 'Competition Venue allocation',
  divisionToFieldLinkage: 'Age Group to Field Linkage',
  fieldSizes: 'Field sizes',
  squadSelection: 'Squad Selection',
  allowHomeAffiliatesToEnterScores: 'Allow Home Affiliates to Enter Attendance and Scores in Web',
  invite: 'Invite',
  send: 'Send',
  noSend: 'No Send',
  tax: 'Tax',
  dragImageToUpload: 'Drag image to upload',
  addType: 'Add type',
  coachSearch: 'Coach Search',
  incident: 'Incidents',
  selectIncident: 'Select Incident',
  _spectator: 'Spectator',
  emailExp: '/^-?(0|[1-9][0-9]*)(.[0-9]*)?$/',
  childDetails: 'Child Details',
  documents: 'Documents',
  addRegDivision: 'Add Registration Age Groups',
  downLoadImportHeading:
    'Download the matches list first then populate referees details to upload ',
  assignUmpireToMatch: 'Assign Referees To Matches',
  participateInCompReg: 'Participating-In Competition Registrations',
  ownedCompetitionsReg: 'Owned Competition Registrations',
  newCompetitionReg: 'New Competition Registration',
  rosterExport: '/roster/export/umpire?',
  Registrations: 'Registrations',
  ladderAllDivisionRmvMsg: "Would you like to set this ladder format for 'All Age Groups'?",
  ladderFormat: 'Ladder Format',
  ladderRemoveMsg: 'Are you sure you want to remove ladder format?',
  competitionEnabled: 'Competition not enabled for Integrated Referees, Click here to enable.',
  bulkScoreUpload: 'Bulk Scores Upload',
  activateFinals: 'Activate Finals',
  allDivisions: 'All Age Groups',
  umpireRoster: 'Referee Roster',
  registrationDivisions: 'Registration Age Groups',
  activeUmpireReserves: 'Activate Referee reserves',
  umpireReserve: 'Referee Reserve',
  points: 'Points',
  reasonForChange: 'Reason For Change',
  editIncident: 'Edit Incident',
  addCompetitionFormat: 'Add Competition Format',
  fileUploadPdf: 'File Upload (File Type: PDF)',
  link: 'Link',
  qrCodeHeader: 'Code from authenticator',
  paymentStatusReference: 'PaymentStatus',
  positionTrackReport: 'Position Tracking Report',
  periodFilter: 'Period',
  byGame: 'By Game',
  importTeamPlayer: 'Import Team and Players',
  matchPrintTemplateType: 'Match Print Template Type',
  templateType: 'Template Type',
  playerBorrowing: 'Player Borrowing',
  borrowPlayer: 'Borrow player',
  gamesBorrowed: 'Games Borrowed',
  minutesBorrowed: 'Minutes Borrowed',
  premierCompLink: 'Premier Competition Link',
  productAddedMessage: 'Product added successfully.',
  productDeletedMessage: 'Product deleted successfully.',
  typeAddedMessage: 'Type added successfully.',
  registrationChange: 'Registration Change',
  cost: 'Cost',
  history: 'History',
  somethingWentWrong: 'Something went wrong.',
  payoutTimedoutError: 'Your report is still being generated, please check back in half an hour!',
  variantDeletedMessage: 'Variant deleted successfully.',
  refreshDownloads: 'Refresh Downloads',
  account: 'Account',
  profileMenu: 'Profile',
  passwordMenu: 'Password',
  profileHeader: 'Your Profile',
  passwordHeader: 'Change your password',
  enterPhoneNumber: 'Enter phone number',
  currentPassword: 'Current password',
  enterCurrentPassword: 'Enter current password',
  newPassword: 'New password',
  enterNewPassword: 'Enter new password',
  confirmPassword: 'Confirm password',
  enterConfirmPassword: 'Enter confirm password',
  userIsRegisteredTo: 'User is registered to',
  competitionAdministrator: 'Competition Administrator',
  regChangeDetail: 'REGISTRATION CHANGE DETAILS',
  dateRegChange: 'Date Registration Change',
  dateCompStart: 'Date Competition Start',
  regChangeType: 'Registration Change Type',
  generateFixtures: 'Generate Fixtures',
  doTheySayForGame:
    'Do they say they have taken the field for training, grading or a competition game?',
  reasonToDeRegister: 'Reasons why they would like to de-register?',
  approvals: 'Approvals',
  approve: 'Approve',
  decline: 'Decline',
  allOrganisation: 'All Organisations',
  individualOrganisation: 'Individual Organisation',
  firstLevelAffiliatesAssociationLeague: '1st Level Affiliates - Association/ League',
  secondLevelAffiliatesClubSchool: '2nd Level Affiliates - Club/ School',
  teamSeasonalFee: 'Team Seasonal Fee',
  instalmentDate: 'Instalment Date',
  addInstalmentDate: '+ Add Instalment date',
  settingsAddedMessage: 'Settings added successfully.',
  deleteVariantOption: 'Delete variant option',
  deleteVariantOptionDescription: 'Please confirm you want to delete this variant option?',
  deleteProductType: 'Delete product type',
  deleteProductTypeDescription: 'Please confirm you want to delete this product type?',
  emailChangedWarning: 'You will need to log in with your new email address on your next login.',
  settingsUpdatedMessage: 'Settings updated successfully.',
  noEnoughUmpireMessage:
    'There are not enough Referees available to alllocate all matches with Referees. You will have matches without Referees allocated. Please review.',
  charity: 'Charity',
  termsAndCond: 'T&Cs',
  whatDoYouWantToPublish: 'What do you want to Publish?',
  ifYouAreUsingIntegratedUmpires:
    'Republishing the Draw will remove Scorer and Referee allocations for those re-published Matches. Please ensure these duties are re-allocated.',
  part: 'Part',
  home_page_heading: 'home_page_heading',
  homeTab: 'home_tab',
  maintain_tab: 'maintain_tab',
  venue_courtId: 'venue&court',
  home_icon: 'home_icon',
  competition_icon: 'competition_icon',
  competitions_label: 'competitions_label',
  registration_icon: 'registration_icon',
  registrations_label: 'registrations_label',
  user_profile_icon: 'user_profile_icon',
  log_out: 'log_out',
  impersonation: 'Impersonation',
  acct_settings_label: 'acct_settings_label',
  help_support_label: 'help&support_label',
  home_table_view: 'home_table_view',
  editRegrade: 'Edit/Regrade',
  fullCompetition: 'Full Competition',
  competitionStartDate: 'Competition Start Date',
  statusPublishHover:
    'This competition needs to be unlocked using the Edit / Regrade option on the competition dashboard in order to be edited',
  teamRankingError: 'Team ranking has not been completed',
  venueSearch: 'Venue Search',
  matchSheetsNoPrintError: 'There is no match sheets to print.',
  selectTemplateTypeError: 'Please select template type.',
  selectTemplateType: 'Select template type',
  liveScoreMatchSheetPreviewModalTitle: 'LiveScores Match Sheet',
  tableMatchID: 'Match ID',
  tableSheetID: 'Sheet ID',
  createdAt: 'Created at',
  download: 'Download',
  downloads: 'Downloads',
  pleaseInputAddress: 'Please input address',
  roundsNotAvailable: 'Rounds not available',
  venueSavedSuccessfully: 'Successfully Saved',
  successMessage: 'Successfully inserted',
  videoSize: 'Selected file must be less then 2 MB',
  video_size: 2048000,
  qcTimeslotNotApplicable: 'Timeslots are not applicable for fixture grid',
  qcVenueConstraintNotApplicable: 'Venue Constraints are not applicable for fixture grid',
  publishModalInfo: 'You have changed the division of the following teams:',
  publishModalConfirmationMsg: 'Would you like to adjust their ladder points?',
  videoSizeMessage: 'The maximum file size can be 2 MB',
  childrenCheckNumber: 'Requires Working with Children Check',
  regenerateDrawTitle: 'Regenerate draw from which Round?',
  impersonationOrgSelect: 'Choose an organization to access',
  numberOfOrders: 'Number of Orders',
  teamRegistrations: 'Team Registrations',
  umpirePayments: 'Referee Payments',
  umpireRate: 'Referee Rate (inc GST)',
  umpire1Rate: 'Referee Rate (inc GST)',
  umpire2Rate: 'Assistant Referee 1 Rate (inc GST)',
  umpire3Rate: 'Assistant Referee 2 Rate (inc GST)',
  umpire4Rate: '4th Official Rate (inc GST)',
  umpireResRate: 'Ref. Reserve Rate (inc GST)',
  umpireCoachRate: 'Ref. Assessor Rate (inc GST)',
  umpirePaymentSetting: 'Referee Payment Settings',
  refundFullAmount: 'Refund Full Amount',
  refundPartialAmount: 'Refund Partial Amount',
  pickedUp: 'Picked up',
  shipped: 'Shipped',
  orderDetails: 'Order Details',
  order: 'Order',
  shippingAndBillingAddress: 'Shipping and Billing Address',
  orderFulfilment: 'Order Fulfilment',
  capturePayment: 'Capture Payment',
  receiptUrl: 'Receipt Url',
  extraTime: 'Extra Time Draw',
  compDeleteConfirm: 'Are you sure you want to delete (COMP_NAME)?',
  addLiveStream: 'Add Live-Stream',
  liveStreamlink: 'Live-Stream Link',
  uponRegistration: 'Upon Registration',
  dateRange: 'Date Range',
  publishToLivescore:
    'Allow Managers, Coaches to be allocated to Teams in Match Day, Referees to be visible (if enabled in Match Day) in the Referee Module and Players in Teams to be able to communicate via the App prior to the draw being Finalised.\n\nPlease note, if Players have been added late to Teams click Yes to push them through to Match Day.',
  finalGrading: 'Make Players, Managers, Coaches and Referees Visible',
  onlyCompMngmt: 'Only Competition Management',
  deletePublishToLsMsg:
    'Are you sure you want to delete (COMP_NAME)? (COMP_NAME) has also been published to Match Day. Would you like to Delete?',
  deleteCompetition: 'Delete Competition',
  enterCode: 'Registration Code',
  finalExtraTime: 'Final Extra Time',
  statusContextMsg: `“Pending Membership” (when the membership fee hasn’t been paid by the individual)\n\n
      “Pending Registration Fee” (when the individual fee is pending)\n\n
      “Registered” (when all fees have been paid)`,
  totalFeeMsg:
    'A fee charged to a player each time they take the field (where the seasonal fee is not being charged).',
  update: 'Update',
  invalidRecords: 'Invalid Records',
  resetLadder: 'Reset Ladder',
  resetLadderConformation: 'Please select one of the following to Reset Ladder',
  selectedDivision: 'Selected Age Group',
  selectedDivisions: 'Selected Age Groups',
  fullReset: 'Full Reset',
  divisionSettings: 'Age Group settings',
  finalMatch: 'Finals Match',
  extra_Time: 'Extra Time',
  extraTimeType: 'Extra Time Type',
  extraTimeqtrBreak: 'Extra Time Quarter Break',
  recordGoalAttempt: 'Record goal attempt',
  mergeCompetition: 'Merge Competition',
  differencesBetween: 'There are some differences between',
  oneHasPreference: 'Which one has preference:',
  divisionAndGrades: 'Age Group and Divisions',
  combine: 'Combine',
  whatRegistrationChange: 'What registration change do you need to make?',
  registrationChangeRef: 'RegistrationChange',
  reasonWhyYourAreDecline: 'Reason why you are declining the request for de-registration?',
  whoPayUmpire: 'Who pays Referees',
  refundAmount: 'Refund Amount',
  toDate: 'To date',
  fromDate: 'From date',
  apply: 'Apply',
  noFixturesMessage: 'No fixtures are available within the provided date range',
  noCompetitionYear: 'There are no competitions for the selected year',
  attendance: 'Attendance',
  umpireAllocationSettings: 'Referee Assignment Settings',
  whoAssignsUmpires: 'Who Assigns Referees',
  affiliateOrganisations: 'Affiliate Organisations',
  noUmpires: 'No Referees',
  takenCourtForTraining: 'Have you taken the field for training, grading or a competition game?',
  exportAttendance: 'Export Attendance',
  exportAttendanceMessage: 'Attendance exported successfully',
  singleUseDiscount: 'Single Use Discount - No Fee Charged',
  singleUseDiscountSubject:
    'Your Single Use discount voucher to use with your Football Registration',
  addCode: 'Add Code',
  go: 'Go',
  matchCalender: 'Match Calendar',
  showByMatches: 'Show By Matches',
  hideFilter: 'Hide Filter',
  showAll: 'Show all',
  competitionDates: 'Competition Dates',
  replicateSetting: 'Replicate Settings',
  venuePreferences: 'Venue Preferences',
  competitionName: 'Competition Name',
  pools: 'Pools',
  gradesOrPools: 'Divisions / Pools',
  gradePoolNames: 'Divisions / Pool Names',
  playOff3rdPosition: 'Playoff for 3rd position',
  whoPlaysWhoValidation: 'Please remove duplicate from who plays who',
  umpireActivity: 'Referee Activity',
  showFilter: 'Show Filter',
  hide: 'Hide',
  importDraws: 'Import Draws',
  heroImageForCompetition: 'Hero Image for Registration Form',
  heroImageSizeText: 'Approximate Dimension: Width: 1200px  Height: 400px',
  poolSettingsWhoPlaysWho: 'Pool Settings - Who Plays Who',
  mailBodyText:
    'Hi,\n \nPlease use the following discount Code when you register in order to have your fee waived.',
  fixtureTemplate: 'Fixture Template',
  reasonForTransfer: 'Reason for Transfer',
  registrationCloseDate: 'Registration close date',
  filterDates: 'Filter Dates',
  showOnlyScheduledMatches: 'Show only scheduled matches',
  showByDivision: 'Show by Age Group/Division',
  invertAxis: 'Invert Axis',
  notAllowed: 'Not allowed',
  uploadBankAccount: 'Upload Bank Account',
  editBankAccount: 'Edit Bank Account',
  theyAlreadyTakenCourt:
    'They have already taken the field for training, grading or a competition game',
  theyOweMonies: 'They owe monies',
  noTeamAvailable: 'No team available',
  suspended: 'Suspended',
  suspendedQuestion: 'How long will this participant be suspended for?',
  reasonWhyYourAreDeclineFromTransfer:
    'Reason why you are declining the request to transfer from your organisation',
  reasonWhyYourAreDeclineToTransfer:
    'Reason why you are declining the request to transfer to you organisation',
  playerImport: 'Import Players',
  atPointOfRegistration: 'At point of Registration',
  nominationFee: 'Nomination Fee',
  nominationFeeTeam:
    'Please note - The manager can choose to pay the nomination fee or can split it with the players at the time of registration',
  paymentMethods: 'Payment Methods',
  paymentMethod: 'Payment Method',
  setMembershipProducts: 'Set Membership Product(s)',
  membershipPaymentOptions: 'MembershipPaymentOption',
  membershipFeesPaymentOptions: 'Membership Fee Payment Options',
  whenPaymentsRequired: 'When Payments are Required',
  Communication: 'Communication',
  fullCashAmount: 'Full cash amount',
  partialCashAmount: 'Partial cash amount',
  squadSelectionEnabled:
    'Squad selection will be disabled for this age group if position tracking is disabled',
  affiliateAddressAddressSelect: 'Please input affiliate address',
  editOrganisationMessage:
    'If you edit the organisations, please ensure all teams are linked to the correct organisation so that managers, scorers, umpires and coaches remain correctly linked to this competition. Would you like to proceed?',
  pleaseEnsureAllMatchesEnded: 'Please ensure all matches have been ended for',
  backToHome: 'Back to home',
  pool: 'Pool',
  reasonRegisterTitle: 'Why would you like to de-register?',
  useRound1Template: 'Use Round 1 template',
  purchase: 'Purchases',
  membershipFeesRepayConfirmMsg:
    'Users have already registered to this membership fee. Do you want to proceed?',
  whichCompetitionSettingPrecedence:
    'Please select which competition’s settings will take precedence',
  quickCompetitionMismatchMsg:
    'The venue you have selected for this fixture grid will override the competition you are merging to',
  regoFormConfirmMsg:
    'Some users may receive this email a second time. Do you want to proceed with an email notification?',
  emailNotificationUpdate: 'Email Notification Update',
  unavailable: 'Unavailable',
  teamGrading: 'Team Grading',
  usernameEmail: 'Username/Email',
  proceedText: 'Proceed',
  categories: 'Categories',
  umpirePaymentExport: '/matchUmpire/payments/export?',
  communicationList: 'Communication List',
  addCommunication: 'Add Communication',
  notification: 'Notification',
  backToCommunication: 'Back to all communication',
  active: 'Active',
  published: 'Published',
  publishedDate: 'Published Date',
  matchDay: 'Match Day',
  matchDayComp: 'Match Day Competitions',
  backToMatchDay: 'Back To Match Day',
  umpireAccreditation: 'Referee Accreditation',
  expiry: 'Expiry',
  incidentExport: '/incident/export?entityId=',
  minNoDays: 'Minimum number of days',
  extendEndDate: 'Extend End Date',
  membershipFeeCap: 'Governing Body Fee Cap',
  perMatchFeesCannotSet:
    "Per match fees per player can't be set as this competition includes unnamed player type",
  applyMembershipProducts: 'Apply to Membership Products',
  allMembershipProducts: 'All Membership Products',
  fromDob: 'From DOB',
  toDob: 'To DOB',
  maxMembershipFeePayable: 'Maximum Membership Fee Payable (excl. GST)',
  becsSetupNotificationTitle: 'BECS Debit setup done',
  becsSetupNotificationBody: 'Congratulations, you have successfully completed BECS debit setup',
  becsAlreadyCompletedMessage: 'BECS setup already done',
  logo_Image_Size: 'Selected file must be less then 2 MB',
  logo_Image_Format: 'Only jpg, jpeg, png, webp formats are supported',
  imageSizeFormatText:
    'Selected file must be less then 2 MB and jpg, jpeg, png, webp formats are supported.',
  childUnlinkMessage:
    'Your Parent needs to re-link your Accounts. Please ask them to press link next to you name in their User Profile.',
  parentUnlinkMessage:
    'Your Child needs to re-link your Accounts. Please ask them to press link next to you name in their User Profile.',
  ok: 'OK',
  tfaSuccessfullyReset: 'TFA was reset successfully',
  errorInTFAReset: 'There was an issue with resetting TFA',
  becsTnC:
    'By providing your bank account details and confirming this payment, you agree to this Direct Debit Request and the Direct Debit Request service agreement, and authorise Stripe Payments Australia Pty Ltd ACN 160 180 343 Direct Debit User ID number 507156 (“Stripe”) to debit your account through the Bulk Electronic Clearing System (BECS) on behalf of Word Sport Action Pty Ltd (the “Merchant”) for any amounts separately communicated to you by the Merchant. You certify that you are either an account holder or an authorised signatory on the account listed above.',
  mergeUser: 'Merge User',
  userToMerge: 'User to Merge',
  possibleMatches: 'Possible Matches',
  possibleMatchesDescription: 'Select the user you want to merge with and press Next',
  merge: 'Merge',
  userMergedSuccessfully: 'User merged successfully',
  selectAllFromThisUser: 'Select all from this user',
  userInformation: 'User Information',
  success: 'Success',
  id: 'ID',
  bankAccount: 'Bank Account',
  pleaseSelectUserToMerge: 'Please select user to merge',
  selectExternalUserRegistration: 'Please select FA ID',
  unableToContinue: 'Unable to continue',
  selectAYear: 'Select a year',
  resetTFA: 'Reset TFA',
  actions: 'Actions',
  ownRegistration: 'Own Registration',
  otherRegistration: 'Other Registration',
  yourProfile: 'Your Profile',
  paidBy: 'Paid by',
  feeType: 'Fee Type',
  paymentType: 'Payment Type',
  totalFeeIncGst: 'Total Fee (inc GST)',
  governmentVoucher: 'Govt. Voucher',
  governmentVoucherStatus: 'Govt. Voucher Status',
  portion: 'Portion',
  redeemVoucher: 'Redeem Voucher',
  cashPaymentReceived: 'Cash Payment received',
  pendingMembership: 'Pending Membership',
  pendingRegistrationFee: 'Pending Registration Fee',
  registered: 'Registered',
  playerRegistration: 'Player Registration',
  coachRegistration: 'Coach Registration',
  teamRegistration: 'Team Registration',
  childRegistration: 'Child Registration',
  pending: 'Pending',
  declined: 'Declined',
  owing: 'Owing',
  enterAddressManually: 'Enter Address Manually',
  addressSearch: 'Address Search',
  returnAddressSearch: 'Return to Address Search',
  games: 'Games',
  singleGameFees: 'Single Game Fees',
  gamesPaid: 'Games Paid',
  gamesRedeemed: 'Games Redeemed',
  gamesToRedeem: 'Games to Redeem',
  howManyGames: 'How many games?',
  divisionRemoveMsg: 'Are you sure you want to remove age group settings?',
  divisionAllDivisionMsg: 'This will clear your other settings. Ok to proceed?',
  manuallyAllocate: 'Manually Allocate',
  allocateViaPools: 'Allocate Via Panels',
  umpireYourOwnTeam: 'Referee Your Own - Team',
  umpireYourOwnOrganisation: 'Referee Your Own - Organisation',
  maxNumberOfMatches: 'Maximum number of matches',
  coachAccreditation: 'Coach Accreditation',
  teamMembers: 'Team Members',
  addTeamMembers: 'Add Team Members',
  refunds: 'Refunds',
  transferId: 'Transfer Id',
  transactionId: 'Transaction Id',
  payoutId: 'Payout Id',
  refundId: 'Refund Id',
  teamMember: 'Team Member',
  addTeamMember: 'Add Team Member',
  addPool: 'Add Panel',
  pleaseEnterPoolName: 'Please Enter Panel Name',
  nationalAccreditationLevelUmpireQ: 'What is your National Referee Accreditation Level ?',
  nationalAccreditationLevelUmpire: 'National Referee Accreditation Level ',
  accreditationUmpire: 'accreditationUmpire',
  payPerMatch: 'Pay per Match',
  teamMemberParentCheck: 'I am the Parent/ Guardian',
  payingForMember: 'I am paying all fees for this member',
  addNewParentGuardian: 'Add New Parent/Guardian',
  newParentOrGuardian: 'New Parent/Guardian',
  emergencyContact: 'Emergency Contact',
  mobileNumber: 'Mobile Number',
  selectedPaymentOption: 'Please select a payment option',
  directDebit: 'Direct Debit',
  creditCard: 'Credit/Debit Card',
  directDebitMsg: 'A transaction fee of 1.5% +30c applies (capped at $10).',
  stripeMandate1: `By providing your bank account details and confirming this payment,
  you agree to this Direct Debit Request and the`,
  stripeMandate2: `, and authorise Stripe Payments Australia Pty Ltd ACN 160 180 343 Direct Debit User ID number 507156(“Stripe”) to debit your account through the Bulk Electronic Clearing System (BECS) on behalf of World Sport Action Pty Ltd (the "Merchant") for any amounts separately communicated to you by the Merchant.You certify that you are either
  an account holder or an authorised signatory on the account listed
  above.`,
  securePaymentMsg: 'There is no payment required',
  securePaymentOptions: 'Secure Payment Options',
  somethingWentWrongErrorMsg: 'Something went wrong.Please contact Administrator',
  tShirtSizeList: 'TShirtSize',
  nationalAccreditationLevelCoachQ: 'What is your National Coach Accreditation Level ?',
  nationalAccreditationLevelCoach: 'National Coach Accreditation Level',
  expiryDate: 'Expiry Date',
  byBadge: 'By Badge',
  byPool: 'By Panel',
  noPoolMsg: 'There are no panels in this competition',
  noUmpirePayments: 'No referee payment through the platform',
  yesUmpirePayments: 'Referee payments through the platform',
  thankYouRegistering: 'Thank you for registering!',
  emailConfirmNewUserMessage:
    'We have sent you an email confirmation with your new login details. Please log in to the website to manage your profile.',
  emailConfirmExistingUserMessage:
    'We have sent you an email confirmation. You can view your registrations and manage your profile on our website.',
  subTotal: 'Sub-total',
  transactionFee: 'Transaction Fee',
  totalPaymentDue: 'Total Payment Due',
  warning: 'Warning',
  removeFromTeam: 'Remove from Team',
  removedFromGame: 'Removed from game',
  addToTeam: 'Add to Team',
  removeFromTeamPopUpMsg: 'Do you want to remove this user from the team?',
  deletePool: 'Delete panel',
  removePoolMsg: 'Are you sure you want to delete this panel?',
  removeMsg: 'Are you sure you want to delete',
  addToAnotherPool: 'Add to another panel',
  removeFromPool: 'Remove from panel',
  addUmpireToPool: 'Add referee to panel',
  toPool: 'to panel',
  umpireAlreadyInPool: 'This referee is already added to this panel.',
  confirmUnassignMsg:
    'This referee is also added to another panel. Would you like to move them to Unassigned section?',
  removeFromAllPools: 'Remove from all panels',
  poolAddedSuccessMsg: 'New panel was added successfully',
  poolRemovedSuccessMsg: 'Panel was removed successfully',
  yourOrder: 'Your Order',
  summaryByParticipant: 'Summary by participant',
  nominationFeesPaid: 'Nomination Fees Paid',
  nominationFeesDeclined: 'Nomination Fees Declined',
  nominationFeesOwing: 'Nomination Fees Owing',
  competitionFeesPaid: 'Competition Fees Paid',
  competitionFeesDeclined: 'Competition Fees Declined',
  competitionFeesOwing: 'Competition Fees Owing',
  affiliateIfApplicable: 'Affiliate (if applicable)',
  userDetailsInvalid: 'User Details Invalid',
  pleaseInputAmount: 'Please input amount',
  cashReceived: 'Cash Received',
  retryPayment: 'Retry Payment',
  parentDetails: 'Parent details',
  noOfRegisteredUsersInfo:
    'Number of individual users who are registered to your organisation or 1st / 2nd level affiliates (if applicable)',
  noOfRegistrationsInfo: 'Note: number of registrations are counted per role / competition',
  maximumAmountPopupTxt:
    'Refund cannot be processed since the requested amount is more than the applicable amount.',
  enterRefundAmount: 'Please enter the amount to be Refunded.',
  enterAmount: 'Enter the Amount',
  partialRefund: 'Partial Refund',
  enterValidAmount: 'Please enter valid amount',

  // Communication
  communicationDetails: 'Communication Details',
  communicationTitle: 'Communication Title',
  enterCommunicationTitle: 'Enter Communication Title',
  communicationBody: 'Communication Body',
  communicationImage: 'Communication Image',
  communicationVideo: 'Communication Video',
  communicationExpiryDate: 'Communication Expiry Date',
  communicationExpiryTime: 'Communication Expiry Time',
  editCommunication: 'Edit Communication',
  cancelDeRegistrtaion: 'Cancel De-registration',
  cancelTransferReg: 'Cancel Transfer registration',
  feeStatus: 'Fee Status',
  regFailedModalMsg: 'Do you want to mark the invoice as failed?',
  regRetryInstalmentModalMsg: 'Do you want to retry the failed instalment?',
  failed: 'Failed',
  wouldYouLikeToApprove: 'Would you like to Approve?',
  regRetryModalMsg: 'Do you want to retry the failed registration?',
  addDivOrGrade: 'Add Age Group/Division',
  markAsFailedReg: 'Mark as Failed Registration',
  addAnotherMembershipCap: 'Add Another Membership Cap',
  successfullyUpdated: 'Successfully updated',

  // LiveScoreAddNew
  allManagers: 'All Managers',
  allScorers: 'All Scorers',
  allManagersAndScorers: 'All Managers and Scorers',
  allUsers: 'All Users',
  individualManager: 'Individual Manager',
  individualScorer: 'Individual Scorer',
  publishPastMatches: 'Publish past matches?',

  // Hard-Coded Title
  communicationDeleteConfirm: 'Are you sure you want to delete this communication?',
  competitionDeleteConfirm: 'Are you sure you want to delete this competition?',
  divisionDeleteConfirm: 'Are you sure you want to delete this age group?',
  matchDeleteConfirm: 'Are you sure you want to delete this match?',
  newsDeleteConfirm: 'Are you sure you want to delete this news?',
  playerDeleteConfirm: 'Are you sure you want to delete this player?',
  teamDeleteConfirm: 'Are you sure you want to delete this team?',
  umpireProceedConfirm:
    'Assigning this referee will unassign them from their current match assignment. Proceed?',
  registrationAddConfirm: 'Do you want to add registration?',
  proceedConfirm: 'You have teams ‘Not in Draw’. Would you still like to proceed?',
  makePaymentsConfirm: 'Are you sure you want to make payments?',
  affiliateDeleteConfirm: 'Are you sure you want to delete this affiliate?',
  timelineToggleConfirm: 'There are unsaved changes. Would you still like to proceed?',

  affiliateName: 'Affiliate Name',
  rank: 'Rank',
  seasonResults: 'Season Results',
  currentGrade: 'Current Division',
  newGrade: 'New Division',
  summary: 'Summary',
  teamNumbers: 'Team Numbers',
  minTeamsGradeOrDivision: 'Min. Teams/Division or Age Group',
  message: 'Message',
  longitude: 'Longitude',
  latitude: 'Latitude',
  liveScoreAddConfirm:
    'By making this change you may cause the draw to duplicate or create a conflict. We strongly recommend you make all match changes in the Competition Management Draws screen. Do you want to Proceed anyway?',
  team1: 'Team 1',
  team2: 'Team 2',
  away: 'Away',
  goalAttempts: 'Goal Attempts',
  recordGoalAttempts: 'Goal Statistics',
  gameTimeTracking: 'Player Rotation',
  enhancedStatistics: 'Enhanced Statistics',
  otherSettings: 'Other Settings',
  playTime: 'Play Time',
  playPercent: 'Play %',
  position: 'Position',
  misses: 'Misses',
  goals: 'Goals',
  attempts: 'Attempts',
  goalPercent: 'Goals%',
  start: 'Start',
  results: 'Results',
  played: 'Played',
  playedAttendance: 'Played?',
  playingAttended: 'Playing?',
  period1: 'Period 1',
  period2: 'Period 2',
  period3: 'Period 3',
  period4: 'Period 4',
  playedFullPeriod: 'Played Full Period',
  playedAtEndPeriod: 'Played at End Period',
  timestamp: 'Timestamp',
  missedPenalties: 'Penalty Misses',
  dateTime: 'Date/Time',
  matchResult: 'Match Result',
  matchStatus: 'Match Status',
  playerName: 'Player Name',
  signature: 'Signature',
  borrowingTeam: 'Borrowing Team',
  teamAliasName: 'Team Alias Name',
  firstUmpireName: 'First Referee Name',
  firstUmpireClub: 'First Referee Club',
  secondUmpireName: 'Second Referee Name',
  secondUmpireClub: 'Second Referee Club',
  stateTitle: 'State',
  nationalTitle: 'National',
  registrationDetailsRequired: 'Registration Details Required',
  medicalHistory: 'Medical History',
  medicareNumber: 'Medicare Number',
  privateInsurance: 'Private Insurance Provider & Number',
  governmentRebate: 'Government Rebate',
  nswActiveKids: 'NSW Active Kids',
  fairPlayVoucher: 'QLD Fair Play Voucher',
  totalFee: 'Total Fee',
  paidAmount: 'Paid Amount',
  membershipFeesGST: 'Governing Body Fees (excl. GST)',
  nominationFeesExclGst: 'Competition Organiser Nomination Fees (excl. GST)',
  competitionFeesExclGst: 'Venue/Competition Fees (excl. GST)',
  affiliateCompetitionFeesExclGst: 'Club/Affiliate Fees (excl. GST)',
  affiliateNominationFeesExclGst: 'Club/Affiliate Nomination Fees (excl. GST)',
  associationNominationFeesExclGst: 'Association Nomination Fees (excl. GST)',
  clubNominationFeesExclGst: 'Club/Affiliate Nomination Fees (excl. GST)',
  genderRestriction: 'Gender Restriction',
  organiser: 'Organiser',
  totalFeeSeasonalIncGst: 'Total Fee - Seasonal (inc GST)',
  totalFeeSingleGameIncGst: 'Total Fee - Single Game (inc GST)',
  form: 'Form',
  regDate: 'Reg. date',
  fee: 'Fee',
  seasonalFeeIncGst: 'Individual User Seasonal Fee (inc GST)',
  bookingId: 'Booking ID',
  customer: 'Customer',
  refundedAmount: 'Refunded Amount',
  umpire1: 'Referee',
  umpire2: 'Assistant Referee 1',
  umpire3: 'Assistant Referee 2',
  umpire4: '4th Official',
  accreditation: 'Accreditation',
  verifiedBy: 'Verified By',
  timeDatePaid: 'Time/Date Paid',
  pay: 'Pay',
  registrationDate: 'Registration Date',
  registeredUser: 'Registered User',
  friendName: 'Friend Name',
  friendStatus: 'Friend Status',
  friendEmail: 'Friend Email',
  friendPhone: 'Friend Phone',
  venueName: 'Venue Name',
  address1: 'Address1',
  address2: 'Address2',
  postalCode: 'Postal Code',
  ofCourts: '# Of Fields',
  historicalGrade: 'Historical Division',
  historicalResult: 'Historical Result',
  errorMessage: 'Error Message',
  onlyEvenNumbersError: 'Only even numbers are allowed',
  line: 'Line #',
  playingUp: 'Playing Up %',

  affiliateFeeNotSet: 'Affiliate fee not set!',
  courtNumbers: 'Field Numbers',
  courtName: 'Field Name',
  subCourt: 'Sub Field',
  overrideVenueTimeslots: 'Apply Configuration By Timeslots?',
  playerAttTeamA: 'Player Att. Team A',
  playerAttTeamB: 'Player Att. Team B',
  breakDuration: 'Break Duration',
  mainBreakDuration: 'Main Break Duration',
  gmtTimezone: 'Timezone GMT',
  mnbPlayerId: 'mnbPlayerId',
  bench: 'Bench',
  noPlay: 'No Play',
  enableUseOfVouchers: 'Enable use of vouchers',
  qldActiveKids: 'QLD Active Kids',
  noValue: 'N/A',
  paidFeeInclGst: 'Paid Fee (incl. GST)',
  pendingFeeInclGst: 'Pending Fee (incl. GST)',
  duePerMatch: 'Due per Match',
  duePerInstalment: 'Due per Instalment',
  invoiceFail: 'Invoice Fail',
  failedInstalmentRetry: 'Failed Instalment Retry',
  failedRegistrationRetry: 'Failed Registration Retry',
  transfer: 'Transfer',
  registrationCap: 'Registration Cap',
  registeredBy: 'Registered By',
  timeline: 'Timeline',
  instalmentPortion: 'Instalment Portion',
  redeemed: 'Redeemed',
  incorrectProductDetails: 'You have entered incorrect product details.',
  voucherOrDiscountCode: 'Voucher/Discount Code',
  cash: 'Cash',
  nominationFeesRefunded: 'Nomination Fees Refunded',
  competitionFeesRefunded: 'Competition Fees Refunded',
  refunded: 'Refunded',
  markAsPaidReg: 'Mark as Paid Registration',
  invoicePaid: 'Invoice Paid',
  invoice: 'Invoice',
  regPaidModalMsg: 'Do you want to mark the invoice as paid?',
  yourRelationship: 'What is your Relationship?',
  userId: 'User ID',
  competitionId: 'Competition ID',
  instalmentRetryModalTxt: 'Please select the payment type to retry.',
  creditCardOnly: 'Credit Card',
  deRegistrationHelpMsg:
    'What is de-registration? I am leaving Football and no longer want to participate in Football. I have not taken the court for training, grading or competition games.',
  transferHelpMsg:
    'What is a transfer? I am wanting to move to another Football Club or Association for the upcoming season.',
  deRegistrationOption1:
    "I am over committed with other activities and can't fit in time for Football",
  deRegistrationOption2: 'I have been injured or for other health reason (not Football related)',
  deRegistrationOption3: 'Decided not to participate in Football',
  deRegistrationOption4: 'Moving to a different geographical area',
  transferOption1: 'Moving to another Football Club or Association for the upcoming season',
  transferOption2: 'No team available in current Club or Association',
  membershipProductCategoryType: 'Football Type',
  membershipProductCategoryTypeShort: 'Football Type',
  membershipProductCategoryRefIdIsRequired: 'Please select Football Type.',
  nationalMembershipProductType: 'National Membership Product',
  applyRegistrationDates: 'Apply Registration Open and Close Dates',
  allowAtMatchFees: 'Allow for "At Match" Fees',
  applyConcurrencyMembershipProductCategory: 'Which Football Types shall it be applied to?',
  openDate: 'Open Date',
  closeDate: 'Close Date',
  appContextual:
    'App - Communication will be saved and available on the News Page of the Play Football App.',
  integratedAllocation: 'Integrated Referee Module',
  doNotSendEmail: 'Receive Football email communications from the club / association / state',
  marketingOptIn:
    'Receive special offers from our sponsors including FREE and/or discounted items, prize giveaways news etc via Football email communications',
  goalsPenalties: 'Penalty Goals',
  assists: 'Assists',
  ownGoals: 'Own Goals',
  yellowCardTD: 'Yellow Card (TD)',
  yellowCard: 'Yellow Card',
  redCard: 'Red Card',
  M: 'M',
  YD: 'YD',
  Y1: 'Y1',
  Y2: 'Y2',
  Y3: 'Y3',
  Y4: 'Y4',
  Y5: 'Y5',
  Y6: 'Y6',
  Y7: 'Y7',
  Y8: 'Y8',
  R1: 'R1',
  R2: 'R2',
  R3: 'R3',
  R4: 'R4',
  R5: 'R5',
  R6: 'R6',
  R7: 'R7',
  R8: 'R8',
  umpireSettingChangeMessage: `You can only enable "Enter scores after the match" if the "Integrated Referee Module" is used.\n\n
                              Would you like to clear your settings for "when scoring will occur"?`,
  enterScoresAfterMsg: 'Please enable Integrated Referees',
  umpireToScore: 'Referee to score',
  titleGames: 'Games',
  titlePeriods: 'Halves',
  titleMinutes: 'Min',
  playedGames: 'Games Played',
  playedPeriods: 'Halves Played',
  playedMinutes: 'Minutes Played',
  unitGames: 'game(s)',
  unitMinutes: 'min(s)',
  unitPeriods: 'half(es)',
  attendanceMaximumNumber: 'Line up Maximum Number',
  squadMaximumNumber: 'Match List Maximum Number',
  postponeMatches: 'Wash out Matches',
  menuGoals: 'Goals',
  goalStatistics: 'Goal Statistics',
  homeTeamPenaltyScore: 'Home Team Penalty Score',
  awayTeamPenaltyScore: 'Away Team Penalty Score',
  enterHomeTeamPenaltyScore: 'Enter Home Team Penalty Score',
  enterAwayTeamPenlatyScore: 'Enter Away Team Penalty Score',
  umpireAvailability: 'Referee Availability',
  subCourtSize: 'Sub-Field Size',
  NumberOfSubCourts: 'Number of Sub-Fields',
  moreThanOneMsg:
    'Please ensure your sub-field configuration does not add up to more than one full field.',
  divOrGrade: 'Age Group/Division',
  gameStatCategoryFoul: 'Discipline',
  allowAnyoneToBeUmpire: 'Allow anyone linked to the competition to be assigned as an referee',
  reselectAtCourtUmpiresMsg1: 'The following referees were recorded at field:',
  reselectAtCourtUmpiresMsg2: `You will need to re-select them from the dropdowns below to ensure they are accurately reflected in the reports.`,
  umpireOrgMissingWarning: 'Referee must be assigned to an organisation',
  umpireNameMissingWarning: 'Referee name cannot be empty',
  externalID: 'FA ID',
  dashboardMembershipHeader: 'Governing Body',
  dashboardMemberShipFeesHeader: 'Governing Body Fees',
  dashboardMemberShipCapHeader: 'Governing Body Cap',
  stateCasualFee: 'Single Game Fee',
  nationalMembershipFee: 'Football Australia Membership Fee',
  stateMembershipFee: 'Member Federation Fee',
  nationalMembershipProductName: 'Football Australia Membership Product',
  stateMembershipProductName: 'Linked Membership Product',
  stateCasualFeeExclGst: 'Single Game Fee (excl. GST)',
  stateMembershipFeeExclGst: 'Member Federation',
  parentStateSeasonFee: 'Linked Member Federation',
  parentStateCasualFee: 'Linked Member Federation Single Game Fee',
  nationalSeasonFee: 'Football Australia',
  nationalCasualFee: 'Football Australia Single Game Fee',
  membershipFeesInvoiceHeader: 'Governing Body Fees',
  competitionFeesInvoiceHeader: 'Venues/Competition Fees',
  pleaseSelectUmpireForUpdate: 'Please select one or more referees to update.',
  umpireAddedMessage: 'Add Referee - Successfully Added',
  umpireEditedMessage: 'Edit Referee - Successfully Edited',
  umpireChangedMatchDayMessage:
    'You have edited a Referee. Please publish this allocation via the Referee module.',
  umpireSettings: 'Referee Settings',
  noOfUmpireAllocated: 'Number of Referees to be Allocated',
  playerRotationLabelText: 'Player Rotation',
  footballAustraliaMoveCompetition: 'Move to a competition',
  enableMoveFACompBtnMsg: 'Move Registrations to a competition',
  moveCompButtonPopoverMessageFA: 'Please select one or more registrations and click this button.',
  externalRegistrationMoveDisabled:
    'Your Member Federation has disabled the ability to move Football Australia Registrations.',
  moveMessageSuccess: 'Sucessfully moved registrations.',
  userRoles: [
    {
      role: 'Player',
      roleId: RegistrationUserRoles.Player,
    },
    {
      role: 'Coach',
      roleId: RegistrationUserRoles.Coach,
    },
    {
      role: 'Referee',
      roleId: RegistrationUserRoles.Umpire,
    },
    {
      role: 'Volunteer',
      roleId: RegistrationUserRoles.Volunteer,
    },
    {
      role: 'Commitee',
      roleId: RegistrationUserRoles.Committee,
    },
    {
      role: 'Other Official/Statistician',
      roleId: RegistrationUserRoles.OtherOfficial,
    },
    {
      role: 'Other Non Player',
      roleId: RegistrationUserRoles.OtherNonPlayer,
    },
  ],
  umpireBlockDeclineDltMsg:
    'This will delete the threshold time for referees and they will be able to accept or decline the match anytime.',
  addOfficials: 'Add Referee / Officials',
  editOfficials: 'Edit Referee / Officials',
  importOfficials: 'Import Referee / Officials',
};

export default AppConstants;
