const StrapiConstants = {
  STRAPI_TOKEN_LOAD: 'STRAPI_TOKEN_LOAD',
  STRAPI_TOKEN_SUCCESS: 'STRAPI_TOKEN_SUCCESS',
  STRAPI_TOKEN_FAIL: 'STRAPI_TOKEN_FAIL',
  STRAPI_TOKEN_ERROR: 'STRAPI_TOKEN_ERROR',

  STRAPI_GET_WEBSITE_LOAD: 'STRAPI_GET_WEBSITE_LOAD',
  STRAPI_GET_WEBSITE_SUCCESS: 'STRAPI_GET_WEBSITE_SUCCESS',
  STRAPI_GET_WEBSITE_FAIL: 'STRAPI_GET_WEBSITE_FAIL',
  STRAPI_GET_WEBSITE_ERROR: 'STRAPI_GET_WEBSITE_ERROR',

  STRAPI_GET_WEB_PAGES_LOAD: 'STRAPI_GET_WEB_PAGES_LOAD',
  STRAPI_GET_WEB_PAGES_SUCCESS: 'STRAPI_GET_WEB_PAGES_SUCCESS',
  STRAPI_GET_WEB_PAGES_FAIL: 'STRAPI_GET_WEB_PAGES_FAIL',
  STRAPI_GET_WEB_PAGES_ERROR: 'STRAPI_GET_WEB_PAGES_ERROR',

  STRAPI_GET_WEB_PAGES_COUNT_LOAD: 'STRAPI_GET_WEB_PAGES_COUNT_LOAD',
  STRAPI_GET_WEB_PAGES_COUNT_SUCCESS: 'STRAPI_GET_WEB_PAGES_COUNT_SUCCESS',
  STRAPI_GET_WEB_PAGES_COUNT_FAIL: 'STRAPI_GET_WEB_PAGES_COUNT_FAIL',
  STRAPI_GET_WEB_PAGES_COUNT_ERROR: 'STRAPI_GET_WEB_PAGES_COUNT_ERROR',

  STRAPI_GET_WEB_PAGE_LOAD: 'STRAPI_GET_WEB_PAGE_LOAD',
  STRAPI_GET_WEB_PAGE_SUCCESS: 'STRAPI_GET_WEB_PAGE_SUCCESS',
  STRAPI_GET_WEB_PAGE_FAIL: 'STRAPI_GET_WEB_PAGE_FAIL',
  STRAPI_GET_WEB_PAGE_ERROR: 'STRAPI_GET_WEB_PAGE_ERROR',
  STRAPI_RESET_WEB_PAGE_FIELDS: 'STRAPI_RESET_WEB_PAGE_FIELDS',

  STRAPI_UPDATE_WEB_PAGE_LOAD: 'STRAPI_UPDATE_WEB_PAGE_LOAD',
  STRAPI_UPDATE_WEB_PAGE_SUCCESS: 'STRAPI_UPDATE_WEB_PAGE_SUCCESS',
  STRAPI_UPDATE_WEB_PAGE_FAIL: 'STRAPI_UPDATE_WEB_PAGE_FAIL',
  STRAPI_UPDATE_WEB_PAGE_ERROR: 'STRAPI_UPDATE_WEB_PAGE_ERROR',

  STRAPI_DELETE_WEB_PAGE_LOAD: 'STRAPI_DELETE_WEB_PAGE_LOAD',
  STRAPI_DELETE_WEB_PAGE_SUCCESS: 'STRAPI_DELETE_WEB_PAGE_SUCCESS',
  STRAPI_DELETE_WEB_PAGE_FAIL: 'STRAPI_DELETE_WEB_PAGE_FAIL',
  STRAPI_DELETE_WEB_PAGE_ERROR: 'STRAPI_DELETE_WEB_PAGE_ERROR',

  STRAPI_CREATE_WEB_PAGE_LOAD: 'STRAPI_CREATE_WEB_PAGE_LOAD',
  STRAPI_CREATE_WEB_PAGE_SUCCESS: 'STRAPI_CREATE_WEB_PAGE_SUCCESS',
  STRAPI_CREATE_WEB_PAGE_FAIL: 'STRAPI_CREATE_WEB_PAGE_FAIL',
  STRAPI_CREATE_WEB_PAGE_ERROR: 'STRAPI_CREATE_WEB_PAGE_ERROR',

  STRAPI_CREATE_WEBSITE_LOAD: 'STRAPI_CREATE_WEBSITE_LOAD',
  STRAPI_CREATE_WEBSITE_SUCCESS: 'STRAPI_CREATE_WEBSITE_SUCCESS',
  STRAPI_CREATE_WEBSITE_FAIL: 'STRAPI_CREATE_WEBSITE_FAIL',
  STRAPI_CREATE_WEBSITE_ERROR: 'STRAPI_CREATE_WEBSITE_ERROR',

  STRAPI_CREATE_WEBSITE_DEFAULTS_LOAD: 'STRAPI_CREATE_WEBSITE_DEFAULTS_LOAD',
  STRAPI_CREATE_WEBSITE_DEFAULTS_SUCCESS: 'STRAPI_CREATE_WEBSITE_DEFAULTS_SUCCESS',
  STRAPI_CREATE_WEBSITE_DEFAULTS_FAIL: 'STRAPI_CREATE_WEBSITE_DEFAULTS_FAIL',
  STRAPI_CREATE_WEBSITE_DEFAULTS_ERROR: 'STRAPI_CREATE_WEBSITE_DEFAULTS_ERROR',

  STRAPI_VALIDATE_WEBSITE_DOMAIN_LOAD: 'STRAPI_VALIDATE_WEBSITE_DOMAIN_LOAD',
  STRAPI_VALIDATE_WEBSITE_DOMAIN_SUCCESS: 'STRAPI_VALIDATE_WEBSITE_DOMAIN_SUCCESS',
  STRAPI_VALIDATE_WEBSITE_DOMAIN_FAIL: 'STRAPI_VALIDATE_WEBSITE_DOMAIN_FAIL',
  STRAPI_VALIDATE_WEBSITE_DOMAIN_ERROR: 'STRAPI_VALIDATE_WEBSITE_DOMAIN_ERROR',

  STRAPI_CREATE_PAGE_TEMPLATE_LOAD: 'STRAPI_CREATE_PAGE_TEMPLATE_LOAD',
  STRAPI_CREATE_PAGE_TEMPLATE_SUCCESS: 'STRAPI_CREATE_PAGE_TEMPLATE_SUCCESS',
  STRAPI_CREATE_PAGE_TEMPLATE_FAIL: 'STRAPI_CREATE_PAGE_TEMPLATE_FAIL',
  STRAPI_CREATE_PAGE_TEMPLATE_ERROR: 'STRAPI_CREATE_PAGE_TEMPLATE_ERROR',

  STRAPI_GET_POSTS_LOAD: 'STRAPI_GET_POSTS_LOAD',
  STRAPI_GET_POSTS_SUCCESS: 'STRAPI_GET_POSTS_SUCCESS',
  STRAPI_GET_POSTS_FAIL: 'STRAPI_GET_POSTS_FAIL',
  STRAPI_GET_POSTS_ERROR: 'STRAPI_GET_POSTS_ERROR',

  STRAPI_GET_POST_LOAD: 'STRAPI_GET_POST_LOAD',
  STRAPI_GET_POST_SUCCESS: 'STRAPI_GET_POST_SUCCESS',
  STRAPI_GET_POST_FAIL: 'STRAPI_GET_POST_FAIL',
  STRAPI_GET_POST_ERROR: 'STRAPI_GET_POST_ERROR',
  STRAPI_RESET_POST_FIELDS: 'STRAPI_RESET_POST_FIELDS',

  STRAPI_UPDATE_POST_LOAD: 'STRAPI_UPDATE_POST_LOAD',
  STRAPI_UPDATE_POST_SUCCESS: 'STRAPI_UPDATE_POST_SUCCESS',
  STRAPI_UPDATE_POST_FAIL: 'STRAPI_UPDATE_POST_FAIL',
  STRAPI_UPDATE_POST_ERROR: 'STRAPI_UPDATE_POST_ERROR',

  STRAPI_DELETE_POST_LOAD: 'STRAPI_DELETE_POST_LOAD',
  STRAPI_DELETE_POST_SUCCESS: 'STRAPI_DELETE_POST_SUCCESS',
  STRAPI_DELETE_POST_FAIL: 'STRAPI_DELETE_POST_FAIL',
  STRAPI_DELETE_POST_ERROR: 'STRAPI_DELETE_POST_ERROR',

  STRAPI_CREATE_POST_LOAD: 'STRAPI_CREATE_POST_LOAD',
  STRAPI_CREATE_POST_SUCCESS: 'STRAPI_CREATE_POST_SUCCESS',
  STRAPI_CREATE_POST_FAIL: 'STRAPI_CREATE_POST_FAIL',
  STRAPI_CREATE_POST_ERROR: 'STRAPI_CREATE_POST_ERROR',

  STRAPI_CREATE_SITE_SETTING_LOAD: 'STRAPI_CREATE_SITE_SETTING_LOAD',
  STRAPI_CREATE_SITE_SETTING_SUCCESS: 'STRAPI_CREATE_SITE_SETTING_SUCCESS',
  STRAPI_CREATE_SITE_SETTING_FAIL: 'STRAPI_CREATE_SITE_SETTING_FAIL',
  STRAPI_CREATE_SITE_SETTING_ERROR: 'STRAPI_CREATE_SITE_SETTING_ERROR',

  STRAPI_GET_SITE_SETTING_LOAD: 'STRAPI_GET_SITE_SETTING_LOAD',
  STRAPI_GET_SITE_SETTING_SUCCESS: 'STRAPI_GET_SITE_SETTING_SUCCESS',
  STRAPI_GET_SITE_SETTING_FAIL: 'STRAPI_GET_SITE_SETTING_FAIL',
  STRAPI_GET_SITE_SETTING_ERROR: 'STRAPI_GET_SITE_SETTING_ERROR',

  STRAPI_UPDATE_SITE_SETTING_LOAD: 'STRAPI_UPDATE_SITE_SETTING_LOAD',
  STRAPI_UPDATE_SITE_SETTING_SUCCESS: 'STRAPI_UPDATE_SITE_SETTING_SUCCESS',
  STRAPI_UPDATE_SITE_SETTING_FAIL: 'STRAPI_UPDATE_SITE_SETTING_FAIL',
  STRAPI_UPDATE_SITE_SETTING_ERROR: 'STRAPI_UPDATE_SITE_SETTING_ERROR',

  STRAPI_GET_SITE_MENUS_LOAD: 'STRAPI_GET_SITE_MENUS_LOAD',
  STRAPI_GET_SITE_MENUS_SUCCESS: 'STRAPI_GET_SITE_MENUS_SUCCESS',
  STRAPI_GET_SITE_MENUS_FAIL: 'STRAPI_GET_SITE_MENUS_FAIL',
  STRAPI_GET_SITE_MENUS_ERROR: 'STRAPI_GET_SITE_MENUS_ERROR',
  STRAPI_RESET_SITE_MENU_FIELDS: 'STRAPI_RESET_SITE_MENU_FIELDS',

  STRAPI_GET_SITE_MENU_LOAD: 'STRAPI_GET_SITE_MENU_LOAD',
  STRAPI_GET_SITE_MENU_SUCCESS: 'STRAPI_GET_SITE_MENU_SUCCESS',
  STRAPI_GET_SITE_MENU_FAIL: 'STRAPI_GET_SITE_MENU_FAIL',
  STRAPI_GET_SITE_MENU_ERROR: 'STRAPI_GET_SITE_MENU_ERROR',

  STRAPI_UPDATE_SITE_MENU_LOAD: 'STRAPI_UPDATE_SITE_MENU_LOAD',
  STRAPI_UPDATE_SITE_MENU_SUCCESS: 'STRAPI_UPDATE_SITE_MENU_SUCCESS',
  STRAPI_UPDATE_SITE_MENU_FAIL: 'STRAPI_UPDATE_SITE_MENU_FAIL',
  STRAPI_UPDATE_SITE_MENU_ERROR: 'STRAPI_UPDATE_SITE_MENU_ERROR',

  STRAPI_DELETE_SITE_MENU_LOAD: 'STRAPI_DELETE_SITE_MENU_LOAD',
  STRAPI_DELETE_SITE_MENU_SUCCESS: 'STRAPI_DELETE_SITE_MENU_SUCCESS',
  STRAPI_DELETE_SITE_MENU_FAIL: 'STRAPI_DELETE_SITE_MENU_FAIL',
  STRAPI_DELETE_SITE_MENU_ERROR: 'STRAPI_DELETE_SITE_MENU_ERROR',

  STRAPI_CREATE_SITE_MENU_LOAD: 'STRAPI_CREATE_SITE_MENUS_LOAD',
  STRAPI_CREATE_SITE_MENU_SUCCESS: 'STRAPI_CREATE_SITE_MENUS_SUCCESS',
  STRAPI_CREATE_SITE_MENU_FAIL: 'STRAPI_CREATE_SITE_MENUS_FAIL',
  STRAPI_CREATE_SITE_MENU_ERROR: 'STRAPI_CREATE_SITE_MENUS_ERROR',

  STRAPI_UPLOAD_IMAGE_LOAD: 'STRAPI_UPLOAD_IMAGE_LOAD',
  STRAPI_UPLOAD_IMAGE_SUCCESS: 'STRAPI_UPLOAD_IMAGE_SUCCESS',
  STRAPI_UPLOAD_IMAGE_FAIL: 'STRAPI_UPLOAD_IMAGE_FAIL',
  STRAPI_UPLOAD_IMAGE_ERROR: 'STRAPI_UPLOAD_IMAGE_ERROR',
};

export default StrapiConstants;
